draft-js-plugins/draft-js-plugins

- src/mentionPlugin/MentionSearch/MentionOption/index.js
- src/mentionPlugin/MentionSearch/MentionOption/styles.js
- src/mentionPlugin/MentionSearch/index.js
Hey @nikgraf,
PR has changes for:
1. Adding hovered state to dropdown options.
2. Adding filtering for mentions, the filtering logic is that text entered by the user can be anywhere in option and it returns first 5 options filtered.
I could not add keyboard handling as keystrokes are handled at level of editor and are currently not communicated over to plugins. Since dropdown is not focused it can not get keyDown event. We should create hook for these events in plugins which can be called by editor.
> feat(Mentions): adding hover state and filtering for mentions

- draft-js-plugins-editor/src/Editor/index.js
If user passed `handleKeyCommand` as props, execute it first on handleKeyCommand.
This code refer to `this.blockRendererFn`.
> Allow user's handleKeyCommand first.

- draft-js-emoji-plugin/src/EmojiSearch/index.js
- draft-js-emoji-plugin/src/modifiers/addEmoji.js
- draft-js-mention-plugin/src/MentionSearch/index.js
- draft-js-mention-plugin/src/modifiers/addMention.js
I suggest we remove the parameter selection from the addEmoji and the addMention modifiers as we can get it from the editorState. Whenever the modifiers are used, we retrieve the selection from the editorState just to pass it on to the function, and it seems better to me to just retrieve it inside the function. 
You could argue that it is possible to pass in another selection than what is in the current editorState (as is done in getSearchText), but for all use cases of the addEmoji and the addMention modifiers we just retrieve the selection from the current editorState. 
(I'm new to doing pull requests, so any feedback to improve is appreciated.)
> Remove unnecessary parameter from addEmoji and addMention modifiers

- draft-js-plugins-editor/src/Editor/index.js
This PR allows to update the editor state from keyBinding functions such as  `handleKeyCommand` or `keyBindingFn`.
import {RichUtils} from 'draft-js';
const createDefaultKeyCommandPlugin = (config = {}) => {
return {
pluginProps: {
handleKeyCommand: (command, getEditorState, updateEditorState) => {
return false;
const editorState = getEditorState();
const newState = RichUtils.handleKeyCommand(editorState, command);
if (newState) {
updateEditorState(newState);
return true;
}
return false;
}
},
};
};
export default createDefaultKeyCommandPlugin;
> Pass editorState getter & setter as param to keyBinding func fix #126

- draft-js-dnd-plugin/src/blockRendererFn.js
- draft-js-dnd-plugin/src/modifiers/onDropBlock.js
- draft-js-dnd-plugin/src/modifiers/onDropFile.js
- draft-js-plugins-editor/src/Editor/__test__/index.js
- draft-js-plugins-editor/src/Editor/index.js
- draft-js-sticker-plugin/src/blockRendererFn.js
This will make plugin system more flexible for future changes.
In the future we can easily extend out the arguments depending on new features that will be available in DraftJS. We even could pass in the whole pluginEditor context (as we had it in the first implementation & @ianstormtaylor suggested) and it would not result in a braking the API.
Yet I don't feel comfortable to expand the API and pass down the whole pluginEditor context until there is a valid use-case.`focus()` came up as a suggestion, but this can easily be done with `forceSelection` on the editorState as well.
I'm curious how you guys feel about it? @juliankrispel @ianstormtaylor @bkniffler 
P.S. I merged it already so I can move on with some refactoring. If there are good arguments against this change I'm happy to revert …
> Hook arguments

- draft-js-mention-plugin/src/mentionSearchStrategy.js
**Bug:**
if you type `@` at the start of content block it will not show mention search. 
**Fix:**
regex now checks if user type `@` as first content block char or after whitespace char
> fix mention regex if content block starts with @

- draft-js-emoji-plugin/src/emojiSearchStrategy.js
- draft-js-plugins-editor/src/Editor/__test__/index.js
- draft-js-plugins-editor/src/Editor/index.js
- Allow https://github.com/draft-js-plugins/draft-js-plugins/issues/156#issuecomment-207060175
- Allow for props to behave like the plugins instead of them overwriting plugin behaviour
I know `createFnHooks` isn't as beautiful as it used to be, but this is an important step. If you come up with a more clever way, please help refactoring it!
The changes will allow something like this:
```
export default function DndPlugin = (options) => {
return {
blockRendererFn: (contentBlock) => {
return {
decorators: [Draggable],
props: {
allowDrag: options.allowDag !== false
}
}
}
}
}
```
The plugin will apply a decorator to all blocks, and also append the allowDrag prop.
> Editor patch

- docs/client/components/pages/Counter/SimpleCounterEditor/index.js
- draft-js-counter-plugin/src/CustomCounter/__test__/index.js
- draft-js-counter-plugin/src/CustomCounter/index.js
- draft-js-counter-plugin/src/index.js
I was looking at the counter plugin and thinking about how rigid it is, so I decided to try to implement a BYOF (Bring Your Own Function) feature so that the user can have more flexibility.
With this PR, the user can simply drop in their own function that takes a plaintext string as input and outputs a numerical count.
I've added tests to illustrate this.
What do you guys think? Yay or nay?
> [Counter Plugin] Added ability to incorporate custom counting functions

- docs/client/components/pages/Counter/CustomCounterEditor/counterStyles.css
- docs/client/components/pages/Counter/CustomCounterEditor/editorStyles.css
- docs/client/components/pages/Counter/CustomCounterEditor/index.js
- docs/client/components/pages/Counter/SimpleCounterEditor/index.js
- docs/client/components/pages/Counter/gettingStarted.js
- docs/client/components/pages/Counter/index.js
- docs/client/components/pages/Counter/styles.css
- docs/client/components/pages/Counter/webpackConfig.js
- docs/client/components/pages/Counter/webpackImport.js
- draft-js-counter-plugin/src/CustomCounter/index.js
- draft-js-counter-plugin/src/LineCounter/index.js
- draft-js-counter-plugin/src/WordCounter/index.js
I've typed up some docs for the counter plugin. In this PR, I also did the following specific things:
1. Used flex box to better layout the configuration parameters section
2. Used normal JS Object instead of Map for the themed editor example
I do want to say that the whole process was kind of tedious and confusing. There are so many import statements required, and I had to do a lot of copy and paste from the other plugins. I think we should improve this in the future. I assume we'll overhaul the entire process after we cut the next release, so I'm excited for that 😄
> [Counter Plugin] Complete Docs

- draft-js-mention-plugin/src/MentionSuggestions/Entry/Avatar/index.js
React v0.14 doesn't support `null`s as render return value in stateless components.
> Fix rendering empty avatars

- draft-js-emoji-plugin/CHANGELOG.md
- draft-js-emoji-plugin/src/EmojiSuggestions/index.js
- draft-js-mention-plugin/CHANGELOG.md
- draft-js-mention-plugin/src/MentionSuggestions/index.js
This takes care of #259 by providing hooks into when the Mention and Emoji suggestions popovers are opened or closed
> adding onOpen/onClose events for MentionSuggestions and EmojiSuggestions

- draft-js-emoji-plugin/src/emojiStyles.css
I'm seeing mispositioned emojis in my projects and in the [draft-js-plugins](https://www.draft-js-plugins.com/) example editor as of an hour ago.
Notice the oversized, askew *(nerd)* and *(tada)* emojis.
I can repro in chrome and firefox - safari isn't polyfilled, errs out, and just renders the unicode character - and some slack peeps were able to repro as well.
I couldn't find any glaring, recent change that would have caused this but haven't had much time to look 😋 
My solution here is just to *center* and *contain* the emoji background images.
I'll follow up with `changelog` changes if this is indeed valid and useful :)
> Fix emoji background styles.

- draft-js-emoji-plugin/src/emojiStyles.css
some emojis get cut in the editor..
this is fixed with `background-size: 100%`:
this should fix #293
> Add `background-size` to emoji

- draft-js-mention-plugin/src/MentionSuggestions/index.js
- draft-js-mention-plugin/src/utils/positionSuggestions.js
This PR fixes mentions' `positionSuggestions` function to work with non-static parents, related to #283 #206 #289.
Note: it introduces a "regression" on screens smaller than 480px. There's used to have a condition that would align the popover to the left in such circumstances. The "universal" implementation would be more complex as it'd need to look for the relative parent's position in the viewport plus some other stuff. I wasn't sure if it's something that should be part of the default implementation. It's probably going to be a requirement for us though, so I'll add it anyway.
> fix mentions positionSuggestions to work with non-static parents

- README.md
- draft-js-plugins-editor/CHANGELOG.md
- draft-js-plugins-editor/package.json
- draft-js-plugins-editor/src/Editor/__test__/index.js
- draft-js-plugins-editor/src/Editor/index.js
Hey, 
Here are some changes/additions I've created while working on the wysiwyg plugins.
I've removed the block decorator feature, as these will unmount/remount blocks on rerender.
I'm passing all plugin editor properties and methods to plugin methods. I know this has been discussed earlier, I now think this makes sense. Also I'm storing all plugins in this.plugins, which makes them available to plugin methods (for example to check if a certain plugin is available while initializing a plugin).
Also, I've created setReadOnly/getReadOnly to change readOnly through the state. This is crucial for nested editors, as while a nested editor is active the outer editor needs to be set to readOnly=true.
> Plugin editor changes for wysiwyg plugins

- draft-js-toolbar-plugin/src/utils/portal.js
when tooltip get too wide for vertical-align to the target, it would overflow to the left of window, some parts of it become invisible. this patch sets state.left = 0
> [wysiwyg:toolbar] keep tooltip visible within window

- draft-js-toolbar-plugin/src/utils/portal.js
With only 100, the toolbar sometimes stays under other fixed elements like modal window dimmers and such.
> Max out zIndex on portal.js

- draft-js-mention-plugin/src/Mention/__test__/index.js
- draft-js-mention-plugin/src/Mention/index.js
When you try to use an `editorState` that was converted from a
`RawDraftContentState`, the assumption that a mention is a `Map` does not
hold.
````js
const contentState = convertFromRaw(instanceOfRawDraftContentState);
const editorState = EditorState.createWithContent(contentState);
this.state = {
editorState: editorState,
}
````
I assume that calling `fromJS` on something that is already a `Map` is a no-op.
Which seems to be the case: https://github.com/facebook/immutable-js/blob/38019326a8d006a45ef48d9c4644e23ea476d298/src/fromJS.js#L28-L36
> Let mentions render with plain JS Object

- draft-js-mention-plugin/src/MentionSuggestions/index.js
- draft-js-mention-plugin/src/index.js
- draft-js-mention-plugin/src/mentionStrategy.js
- draft-js-mention-plugin/src/mentionSuggestionsStrategy.js
- draft-js-mention-plugin/src/modifiers/addMention.js
Addresses https://github.com/draft-js-plugins/draft-js-plugins/issues/253#issuecomment-227144837.
Adds `mentionTrigger` to `config` with default value of `@`.
Adds and searches for mention entities with key of `'mention' + mentionTrigger`
`mentionStrategy` and `mentionSuggestionsStrategy` takes the trigger as a parameter.
Feedback welcome
> adding mentionTrigger 

- docs/client/components/pages/Mention/CustomMentionEditor/index.js
- docs/client/components/pages/Mention/CustomMentionEditor/mentions.js
- docs/client/components/pages/Mention/CustomMentionEditor/mentionsStyles.css
- docs/client/components/pages/Mention/index.js
- draft-js-mention-plugin/src/MentionSuggestions/Entry/defaultEntryComponent.js
- draft-js-mention-plugin/src/MentionSuggestions/Entry/index.js
- draft-js-mention-plugin/src/MentionSuggestions/index.js
This PR adds a `entryComponent` option to `MentionSuggestions` that provides a way to have a custom template for each suggestions' entry. You can have a look at what it looks like from the documentation (I've updated the custom mention editor example to include an usage example).
> Add a way to provide a custom component for the suggestions' entry

- README.md
`$ npm install draft-js-plugins-editor@beta --save` threw a `No version match found for ...` error.
> update 2.0.0 beta usage instructions.

- README.md
`$ npm install <plugin>@beta --save` also throws a `no version match` error.
Should have assumed as much but didn't get round to actually installing any plugins until now, sorry!
> update beta plugin usage instructions.

- draft-js-sticker-plugin/src/selectStickerStyles.css
Vendor Prefix included because autoprefixer won't catch that one.
See #374
> MOD: to prevent the user from dragging the sticker

- FAQ.md
This PR corrects a few typos in the mention plugin FAQ.
> Correct typos in mention plugin FAQ

- draft-js-linkify-plugin/src/Link/index.js
- draft-js-linkify-plugin/src/index.js
This adds a configuration key 'component', which can be used to enhance the default one
with additional properties like event handlers, or inline style.
In other words, this is the #271 for the Linkify plugin.
> feat(Linkify): Allow the Linkify plugin to accept a custom component

- draft-js-counter-plugin/src/CustomCounter/index.js
`PropTypes.function` is incorrect. It should be `PropTypes.func`.
Also a `CustomCounter` without a `count` function doesn't really make sense. So I've marked the `countFunction` as being required.
> Fix incorrect PropType specification in CustomCounter

- draft-js-mention-plugin/src/MentionSuggestions/index.js
I noticed that using the Mentions plugin from npm, the build version disregards the `entryComponent` prop. Seems to be related to `defaultProps` & the webpack build.
in this PR i removed the `defaultProps` and set entryComponent to be `props.entryComponent || defaultEntryComponent`
thanks
> Fix Build for Mention Suggestions

- draft-js-mention-plugin/src/MentionSuggestionsPortal/index.js
When inputting Japanese characters (or any complex alphabet which requires hitting enter to commit the characters), that action was causing a race condition. By changing componentWillMount to componentDidMount, this issue is resolved and the component will unmount unregister and then properly mount and register after. Prior to this change, componentWillMount would not fire after componentWillUnmount even though it was still in the DOM, so it wasn't re-registering the offsetkey.
> Fixes race condition with Japanese input

- docs/webpack.config.dev.js
- package.json
I added babel polyfill to the demo/website so it supports IE10:
Fix #459
> Add babel polyfill to support older browser

- draft-js-dnd-plugin/package.json
- draft-js-dnd-plugin/src/modifiers/addBlock.js
- draft-js-dnd-plugin/src/modifiers/onDropBlock.js
- in the case where the Entity associated with the given block is of a custom type, the current onDropBlock function overwrites the Entity type with whatever type the ContentBlock is
- this commit allows optional specification of entity type in the addBlock modifier function, meaning the newly created Entity will be typed correctly as it was before being dragged-n-dropped
- if unspecified in the addBlock modifier function, it will fallback to the old behaviour of creating an Entity with whatever type the ContentBlock was using
- tests and linting passing; no build errors
- I have an atomic-typed ContentBlock associated with a Entity of type 'blah'
- dragging and dropping that block somewhere else will recreate the Entity in the new selection but replace the type with 'atomic', as that's …
> Fix for DND onDropBlock overwriting custom Entity types

- docs/client/components/pages/Sticker/index.js
Fix typo: Finish sentence for `stickerImage` in API docs.
> [docs][draft-js-sticker-plugin] Fix typo

- docs/client/components/pages/Mention/index.js
- draft-js-mention-plugin/CHANGELOG.md
- draft-js-mention-plugin/src/Mention/index.js
- draft-js-mention-plugin/src/MentionSuggestions/index.js
- draft-js-mention-plugin/src/index.js
- draft-js-mention-plugin/src/modifiers/addMention.js
mentionPrefix is not in editorState since it's added as a plain text node, not draft editor node. This creates a problem when the plugin is used with CharCounter. (See example https://drive.google.com/open?id=0B3Ftrnd9yXx-SzQ2YndPR0g4YW8)
I'm not sure if this behavior is intentional. Feedback needed.
> [draft-js-mention-plugin] mentionPrefix as part of draft editor node

- draft-js-mention-plugin/src/MentionSuggestions/index.js
Without this props in render method of MentionSuggestions component you may have warning:
_`Warning: Unknown props `onOpen`, `onClose` on <div> tag`_
> add missing props to render of MentionSuggestions

- FAQ.md
Related to https://github.com/draft-js-plugins/draft-js-plugins/issues/352
@nikgraf `can you add that to the documentation somehow? e.g. to the FAQ.md` :P
> Adds a "how to" on shimming polyfills for IE11

- draft-js-inline-toolbar-plugin/src/components/Toolbar/index.js
Bug reproduction:
1. select a word
2. click outside editor
3. click in the editor, not in a text
> bugfix position toolbar on focus

- draft-js-inline-toolbar-plugin/src/components/Toolbar/index.js
- draft-js-inline-toolbar-plugin/src/utils/__test__/createStore.js
- draft-js-inline-toolbar-plugin/src/utils/createStore.js
Adds functionality for unsubscribing from listeners to items in store for inlineToolbar plugin.
Fixes #519
> Unsubscribe from store - inlineToolbar plugin

- docs/client/components/pages/InlineToolbar/webpackImport.js
Fixes a typo in the documentation to properly import the css for the inline toolbar.
> [Docs] [inline-toolbar] Fix css import typo

- draft-js-inline-toolbar-plugin/src/components/Toolbar/index.js
The inline toolbar plugin is currently positioned absolutely but the offset assumes there are no containers between the toolbar and the document body with a position other than `static`
This PR re-uses the `getRelativeParent` function from the mention and emoji plugins to correct the positioning of the toolbar to fix #531
Whilst the alternative fix in PR #617 is much better than it is at the moment, using `position: fixed` means that if the user scrolls whilst something is selected the toolbar follows them down the page.
I think/hope this PR creates a nicer experience.
> Fix inline toolbar positioning to work with a relative parent fixes #531

- draft-js-emoji-plugin/src/emojiStyles.css
Currently if you highlight the emojione emoji's, the highlight bar disappears. With these changes however you get a nice continuous highlight so you can actually see what you are selecting.
> [emoji-plugin] Make emoji highlightable

- draft-js-emoji-plugin/src/EmojiSuggestions/index.js
Fixes the following runtime warning:
Steps to reproduce:
1. Use `EmojiSuggestions` with an `onOpen`, `onSearch`, or `onSearchChange`
2. Upon opening emoji suggestions for first time, see the above warning in javascript console.
> Fix EmojiSuggestions unknown props on `<div>` for `on*` callbacks

- CONTRIBUTING.md
We came across some changes to our webpack configuration that were necessary in order to develop on the mention plugin specifically. The changes are summarized here.
> Add more instructions for development forks.

- draft-js-mention-plugin/src/MentionSuggestionsPortal/index.js
Fixes issue #666.
I'm not entirely sure why this makes a difference. I suspect it's a timing issue in React. Ideally, we shouldn't be accessing refs outside of the React lifecycle functions, so accessing this in a closure like this may cause problems again in the future if React internals change.
> Move searchPortal ref function to constructor

- docs/client/components/pages/Mention/index.js
- draft-js-mention-plugin/src/MentionSuggestions/__test__/index.js
- draft-js-mention-plugin/src/MentionSuggestions/index.js
This allows you to override the `<div />` used to render the mention
suggestions in.  A use case is to replace the `<div />` with MaterialUI's
`<Paper />` for design coherency.
> Support popoverComponent on MentionSuggestions

- draft-js-mention-plugin/src/MentionSuggestions/__test__/index.js
- draft-js-mention-plugin/src/MentionSuggestions/index.js
- draft-js-mention-plugin/src/MentionSuggestionsPortal/index.js
- draft-js-mention-plugin/src/index.js
I tried out mentions plugin and noticed that it inserts selected item on `Enter` or `Tab` when there's no trigger in sight and dropdown is not rendered. After reading the code, this is the first solution I came up with. Also, I was thinking about using `null` value for `focusedOptionIndex` when dropdown is not visible, but it's a bit implicit and I've already implemented the current fix, so I'd get feedback from maintainers first.
There's a chance that both directions are suck :) due to lack of my familiarity with this code base (and with draft js in general, yet). So I'll be happy to implement it in the right way after feedback from maintainers.
> [mentions]: prevent selection commit on Tab/Enter if dropdown is not rendered

- draft-js-alignment-plugin/src/AlignmentTool/index.js
We fixed the positioning of the inline toolbar a while ago to work well with relative parents, but the alignment plugin toolbar still had the same problem. So I changed the positioning logic of the alignment plugin to work the same way.
> Fix the positioning of the alignment plugin to work the same way as the inline-toolbar works

- draft-js-mention-plugin/src/MentionSuggestions/index.js
Hi,
I've removed lines calling `MentionSuggestions#openDropdown` in `componentWillReceiveProps` that caused unintended method binding.
This caused a bug that selects candidate on hitting return key even if the dropdown was closed.
> Do not openDropdown in componentWillReceiveProps

- draft-js-plugins-editor/src/Editor/index.js
As discussed in #660.
I've changed all the `for of` loops were possible to `forEach`. I noticed there were some loops where there was a return statement. As these can't be handled with `forEach`, I've changed them to basic `for` loops that iterate over a counter variable.
The file `src/Editor/index.js` seems to be the only file where `for of` loops occur – I've searched through the code base with a regex.
Currently the test "MentionSuggestions Component: The popoverComponent recieves the children" fails, but that seems to be unrelated to this PR.
> Replaced `for of` loops with alternatives.

- draft-js-side-toolbar-plugin/src/components/Toolbar/index.js
The positioning of the side toolbar was broken in IE11, as `window.scrollY` isn't available there. This fixes the issue.
> Fix positioning of side toolbar in IE11.

- draft-js-undo-plugin/src/RedoButton/index.js
- draft-js-undo-plugin/src/UndoButton/index.js
UNdo/Redo Button is disabled when => store is not initialized, or redo stack is empty.
Added an existence check of store to the Undo/Redo button
https://github.com/draft-js-plugins/draft-js-plugins/issues/718
> Fix the Undo/Redo Button initialize issue

- draft-js-emoji-plugin/src/components/EmojiSelect/Popover/index.js
When I replaced scroll component in `EmojiSelect` component from `draft-js-emoji-plugin`, I missed that it was used when ToneSelect opens.
> Fix open tone select issue

- draft-js-undo-plugin/src/RedoButton/index.js
- draft-js-undo-plugin/src/UndoButton/index.js
This fixes #718. 
Checks that `this.props.store.getEditorState` actually exists in `UndoButton` and `RedoButton`.
Now `UndoButton` and `RedoButton` can be placed above the editor as they're no longer dependent on `store.getEditorState` existing on first render.
> Check that store.getEditorState exists in UndoButton and RedoButton

- docs/webpack.config.base.js
- draft-js-emoji-plugin/webpack.config.js
Fix issue https://github.com/draft-js-plugins/draft-js-plugins/issues/748
Add `sass-loader` to `draft-js-emoji-plugin/webpack.config.js`
> Add sass-loader to emoji-plugin webpack config

- draft-js-plugins-editor/CHANGELOG.md
Remove the following duplicated entries. This sentence was appeared 3 times.
> `handleBeforeInput` now receives the arguments `(chars, editorState, pluginFunctions)`
> Remove duplicated entries in the changelog

- docs/client/components/pages/InlineToolbar/CustomInlineToolbarEditor/editorStyles.css
- docs/client/components/pages/InlineToolbar/CustomInlineToolbarEditor/index.js
- draft-js-inline-toolbar-plugin/src/components/Toolbar/__test__/Toolbar.js
- draft-js-inline-toolbar-plugin/src/components/Toolbar/index.js
- draft-js-inline-toolbar-plugin/src/index.js
This allows buttons of the inline toolbar to render dynamic content into the toolbar. An example is the ability to add links directly from the toolbar (see demo).
This could be a first step for a robust plugin to add links. Currently we have #610, but that touches quite a few files and got released in a [separate repository](https://github.com/vacenz/last-draft-js-plugins) anyway. This PR is inspired by the implementation of the toolbar plugin over there, but is agnostic to what kind of content can be rendered in the toolbar.
In this case, I've got a `AddLinksButton` component in the `structure` for the toolbar. When the button is clicked, it calls `this.props.onOverrideContent(AddLinkForm);` to render the form. The form can use the same method for reverting back to the normal state.
I …
> Add feature to inline toolbar that allows for children to override the content.

- draft-js-linkify-plugin/package.json
Update `linkify-it` to `^2.0.3` and `tlds` to `^1.189.0` for linkify-plugin.
Nothing.
Nothing.
> Update dependencies for linkify-plugin

- draft-js-plugins-editor/package.json
Please tell if the `~` is intended :)
Allow not just immuatable 3.7.4 but alos 3.8.x etc
> Allow immutable 3.8.x as well

- draft-js-alignment-plugin/src/createDecorator.js
Fix #639 & #763 : deleting the block still shows the toolbar
> Fix #639 & #763 : Alignment plugin , deleting the block still shows the toolbar

- draft-js-emoji-plugin/src/constants/defaultEmojiGroups.js
By using direct imports, this should cut down on bundle size.
Fixes #753
> Use direct imports for react-icons in emoji-plugin

- draft-js-plugins-editor/src/Editor/index.js
Hi there,
I'm getting the following warning logged to the console when using `draft-js-plugins-editor@2.0.0-rc2`.
```
VM110896:4655 iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
at List.get (eval at <anonymous> (https://localhost:3000/ng/embed.js:1386:1), <anonymous>:4650:21)
at List.slice (<anonymous>)
at Function.Array.from (https://testhorse.dev-ben.seamlessdocs.com/_js/mootools-compat-1.4.5.js:136:105)
at _toConsumableArray (eval at <anonymous> (https://localhost:3000/ng/embed.js:15309:1), <anonymous>:49:182)
at PluginEditor.componentWillMount (eval at <anonymous> (https://localhost:3000/ng/embed.js:15309:1), <anonymous>:104:67)
at eval (eval at <anonymous> …
```
> Fix deprecation warning: stop treating Immutable.List like an Array

- draft-js-mention-plugin/src/MentionSuggestions/index.js
Using the latest versions of React and DraftJs when using the up/down arrow keys it wasn't properly selecting the appropriate items
> onMentionFocus wasn't properly setting state using `setState`

- draft-js-inline-toolbar-plugin/src/components/Toolbar/index.js
- it takes toolbar buttons out of the tab order, when are hidden
Hide toolbar with visibility property, browser then ignore buttons whenpage is walked throught tab. 
same as https://github.com/draft-js-plugins/draft-js-plugins/pull/647
- [ x] Enable "Allow edits from maintainers" for this PR
> hide inline toolbar if is not visible using css visibility

- FAQ.md
Add `Array.fill` polyfill to the list of polyfills required for IE11
You can see the usage of it [here](https://github.com/draft-js-plugins/draft-js-plugins/blob/a571b3d10b1022199a56e42723f23ff2cb477a9c/draft-js-plugins-editor/src/Editor/MultiDecorator.js#L17).
> Update polyfill list for IE11 in FAQ

- draft-js-inline-toolbar-plugin/src/components/Toolbar/__test__/Toolbar.js
- draft-js-inline-toolbar-plugin/src/components/Toolbar/index.js
- Fixed inline toolbar not disappearing when editor loses focus (blur) [Video of the bug](https://drive.google.com/file/d/0B4McFs23KX_VdnFsbmc2c0hDX1E/view?usp=sharing)
- Fixed test for inline toolbar
[Demo of the fix](https://drive.google.com/file/d/0B4McFs23KX_VdWlNU1N5LVpMTGc/view?usp=sharing)
//
> Hide inline toolbar on editor blur

- draft-js-image-plugin/src/modifiers/addImage.js
We need to keep a reference to the actual file object around in our app, which is currently impossible as we have to use `URL.createObjectURL` to get a URL suitable to be passed as a `src`.
This patch allows us to keep that reference in `entity.data` like so:
```JS
onChange(addImage(state, URL.createObjectURL(file), { file: file }));
```
Without this we can't upload the images to a remote server (in our case S3) since we can't do that with just the URL. By allowing extra data to be passed through to the entity this becomes possible.
> Allow passing extra data with addImage call

- draft-js-emoji-plugin/src/components/EmojiSelect/index.js
Fix for issue #781 
By default buttons inside nested forms when clicked submit the form. Adding type="button" fixes the issue.
> Add type="button" to emoji select to prevent submitting when placed inside a form.

- docs/client/components/pages/Emoji/index.js
- draft-js-emoji-plugin/src/components/Emoji/index.js
- draft-js-emoji-plugin/src/components/EmojiSelect/Popover/Entry/index.js
- draft-js-emoji-plugin/src/components/EmojiSelect/Popover/Groups/Group/index.js
- draft-js-emoji-plugin/src/components/EmojiSelect/Popover/Groups/index.js
- draft-js-emoji-plugin/src/components/EmojiSelect/Popover/index.js
- draft-js-emoji-plugin/src/components/EmojiSelect/index.js
- draft-js-emoji-plugin/src/components/EmojiSuggestions/Entry/index.js
- draft-js-emoji-plugin/src/components/EmojiSuggestions/index.js
- draft-js-emoji-plugin/src/index.js
This allows displaying the native emoji art instead of EmojiOne art for emoji plugin.
#756 
You can change between native and EmojiOne art by passing useNativeArt for emoji plugin when initializing.
```javascript
import React, { Component } from 'react';
import Editor, { createEditorStateWithText } from 'draft-js-plugins-editor'; // eslint-disable-line import/no-unresolved
import createEmojiPlugin from 'draft-js-emoji-plugin'; // eslint-disable-line import/no-unresolved
import editorStyles from './editorStyles.css';
const emojiPlugin = createEmojiPlugin({
useNativeArt: true
});
const { EmojiSuggestions, EmojiSelect } = emojiPlugin;
const plugins = [emojiPlugin];
const text = `Cool, we can have all sorts of Emojis here. 🙌
🌿☃️🎉🙈 aaaand maybe a few more here 🐲☀️🗻 Quite fun!`;
export default …
```
> Add native art display possibility for emojis.

- draft-js-anchor-plugin/src/components/Link/index.js
So I ended up closing the other PR which had this change, but I pulled down the repo and ran the PropTypes codemod across the project, and this was the only update it found.
I also locally upgraded to React 16 beta, and I found that the anchor plugin was the only thing causing an error, so I'm pretty confident this is the only Component which uses PropTypes from the React package instead of `prop-types`.
> Use propTypes from external package in anchor-plugin

- draft-js-mention-plugin/CHANGELOG.md
- draft-js-mention-plugin/src/MentionSuggestions/index.js
We've fixed async loading of suggestions (the issue here https://github.com/draft-js-plugins/draft-js-plugins/issues/633) by re-opening the dropdown when the `MentionSuggestions` component receives non-empty suggestions (see https://github.com/draft-js-plugins/draft-js-plugins/pull/807/files). 
This incorrectly opens the dropdown also when the component is re-rendered, but suggestions have not changed.
I'm adding a check that the suggestions have actually changed.
Run the docs locally, focus the editor on the front page and hit enter a couple of times or try to at-mention "@ i i i i". Both issues are solved.
Fixes https://github.com/draft-js-plugins/draft-js-plugins/issues/825
Fixes https://github.com/draft-js-plugins/draft-js-plugins/issues/857
> Fix incorrect opening of suggestions

- CONTRIBUTING.md
- docs/client/components/pages/Alignment/webpackConfig.js
- docs/client/components/pages/Counter/webpackConfig.js
- docs/client/components/pages/DragNDrop/webpackConfig.js
- docs/client/components/pages/Emoji/webpackConfig.js
- docs/client/components/pages/Focus/webpackConfig.js
- docs/client/components/pages/Hashtag/webpackConfig.js
- docs/client/components/pages/Image/webpackConfig.js
- docs/client/components/pages/InlineToolbar/webpackConfig.js
- docs/client/components/pages/Linkify/webpackConfig.js
- docs/client/components/pages/Mention/webpackConfig.js
- docs/client/components/pages/Resizeable/webpackConfig.js
- docs/client/components/pages/SideToolbar/webpackConfig.js
- docs/client/components/pages/StaticToolbar/webpackConfig.js
- docs/client/components/pages/Sticker/webpackConfig.js
- docs/client/components/pages/Undo/webpackConfig.js
- docs/client/components/pages/Video/webpackConfig.js
- draft-js-counter-plugin/README.md
- draft-js-emoji-plugin/README.md
- draft-js-hashtag-plugin/README.md
- draft-js-linkify-plugin/README.md
- draft-js-mention-plugin/README.md
- draft-js-sticker-plugin/README.md
- draft-js-undo-plugin/README.md
https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
> Add loader module name extension

- draft-js-mention-plugin/CHANGELOG.md
- draft-js-mention-plugin/src/defaultRegExp.js
- Adding support for Latin-1 Supplement and Latin Extended-A characters to the `defaultRegExp` in mentions plugin to allow searching European names.
- I've also replaced the `\w` with `a-zA-Z0-9-` (support `-` instead of `_`)
- Further I've split the regex into multiple strings and ordered them roughly by occurance in the unicode table.
Let me know if you'd like me to change anything.
Add names like Anna Glöckner, María-Jose Quiñones, László Horvát or Linnéa Månsson to mentions.js in the simple editor example. You'll only be able to search them with the extended regex.
> Add support for missing latin characters

- docs/client/components/pages/Mention/CustomComponentMentionEditor/index.js
- docs/client/components/pages/Mention/CustomMentionEditor/index.js
- docs/client/components/pages/Mention/RemoteMentionEditor/index.js
- docs/client/components/pages/Mention/SimpleMentionEditor/index.js
As discussed in https://github.com/draft-js-plugins/draft-js-plugins/issues/298, a few people have  accidentally used the same `createMentionPlugin()` plugin for multiple editor components. This happens because they expect the [examples in the docs](https://www.draft-js-plugins.com/plugin/mention) to work, even if there are multiple instances of the editor component on the same page. While this is [mentioned in the FAQ](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#can-i-use-the-same-plugin-for-multiple-plugin-editors), it would be helpful to mention also this in the documentation.
What are the disadvantages to always assigning the plugin instance to a property on the component? If you don't want to suggest this for the typical use case, I can change this PR to …
> Update mention documentation to assign plugin instance to property

- draft-js-image-plugin/CHANGELOG.md
- draft-js-image-plugin/src/index.js
All this does is introduce a check to make sure we don't crash the
editor when no entity with a certain ID is found.
Closes #778
> Fix critical bug in image plugin

- draft-js-focus-plugin/CHANGELOG.md
- draft-js-focus-plugin/src/index.js
- draft-js-focus-plugin/src/modifiers/insertNewLine.js
fixes #885 
Current behaviour: when i press enter on a focused block the newline is generated before the block
Now: the newline is generated after the focused block
> fix for newline when focusable atomic block is selected

- draft-js-emoji-plugin/CHANGELOG.md
- draft-js-emoji-plugin/package.json
- draft-js-emoji-plugin/src/components/Emoji/index.js
fixes #886
The problem is that we weren't using `props.children` for the decorated component, that screws up draft-js internal logic...
Native emojis are working again:
> fix native emojis

- docs/client/components/pages/Mention/CustomMentionEditor/index.js
- draft-js-mention-plugin/CHANGELOG.md
- draft-js-mention-plugin/src/MentionSuggestions/Entry/index.js
This is a proposal to pass through the `isFocused` prop to the mention entry. This is useful for people who are not using classNames for styling e.g. when using `styled-components`.
Currently I need to do the following in my entry component for determining wether it is focused:
```javascript
const isFocused = className === theme.mentionSuggestionsEntryFocused;
```
> Pass through isFocused prop to mention entry

- draft-js-anchor-plugin/CHANGELOG.md
- draft-js-anchor-plugin/package.json
Functionality of the packages has already been removed previously, but the packages were not removed from the package.json.
Previous published Lib of the draft-js-anchor-plugin does not reflect current project state (still uses package ip-regex), and needs to be refreshed.
As discussed with @juliankrispel over [Draft.js Slack](https://draftjs.slack.com/)
Removed unused packages from package.json to tidy up and to trigger a new publish procedure.
No demo for removed packages.
> Remove unused packages from project and trigger fresh publish

- draft-js-drag-n-drop-plugin/src/createDecorator.js
While I still don't know why or how this can happen, this should at least make it so the breaking #926 bug doesn't happen anymore.
> Fix draft-js-drag-n-drop plugin

- draft-js-emoji-plugin/src/components/EmojiSuggestions/index.js
Same issue as https://github.com/draft-js-plugins/draft-js-plugins/pull/762 but for the emoji suggestions.
> onEmojiFocus wasn't properly setting state using `setState`

- HOW_TO_CREATE_A_PLUGIN.md
- docs/client/components/pages/StaticToolbar/SimpleToolbarEditor/index.js
- docs/client/components/pages/StaticToolbar/index.js
There's a typo in the guide (willUnMount -> willUnmount) and the documentation for the static toolbar was copied from the inline toolbar without being properly updated.
> Fix typos and copy/paste errors in plugin guide and examples for the static toolbar.

- draft-js-image-plugin/CHANGELOG.md
- draft-js-image-plugin/package.json
- draft-js-image-plugin/src/modifiers/addImage.js
Right now, when you insert an image the cursor is afterwards _above_ the image, rather than below it. With this fix the cursor is correctly moved after the image, which makes for a much nicer writing experience.
> Move cursor after image when inserting

- draft-js-buttons/src/index.js
- draft-js-buttons/src/utils/createOnClickButton.js
Add a toolbar button that calls an onClick prop when clicked. 
This implementation follows the other createXX Button HOCs to create a button that just triggers a callback that can be used to show popups etc for the user.
> Add support for clickable buttons

- FAQ.md
- draft-js-plugins-editor/CHANGELOG.md
- draft-js-plugins-editor/package.json
- draft-js-plugins-editor/src/Editor/__test__/index.js
- draft-js-plugins-editor/src/Editor/index.js
- draft-js-plugins-editor/src/Editor/resolveDecorators.js
We add decorators to the editorState upon initalisation of the Editor but not when props update. This fixes this!
fixes #359 
fixes #262
> Add missing decorators to editorState when props update

- draft-js-plugins-editor/src/Editor/index.js
The latest release of the editor introduced an infinite loop with the
componentWillReceiveProps decorator fixes.
This patch resolves the infinite loop by explicitly checking for size
changes, and making sure to not call `onChange` when the new editor
state has decorators.
> Resolve infinite loop

- draft-js-plugins-editor/CHANGELOG.md
- draft-js-plugins-editor/package.json
This PR fixes a small glitch in immutable.js dependency version range that causes yarn (for example) to install multiple unnecessary versions of immutable.js when this plugin is in use.
> draft-js-plugins-editor: fix immutable.js dependecy to match other plugins

- draft-js-image-plugin/CHANGELOG.md
- draft-js-image-plugin/src/Image/index.js
https://github.com/draft-js-plugins/draft-js-plugins/issues/1032
When using draft-js version 0.10.5 an extra prop `blockStyleFn` is passed and needs to be omitted like the others otherwise it is assigned as an elementProp and causes the error
`Unknown prop 'blockStyleFn' on <img> tag`
Solution is to add this `blockStyleFn` prop to the omitted props list so it is not assigned as an elementProp
> Omit blockStyleFn prop from list of elementProps in image plugin

- draft-js-mention-plugin/CHANGELOG.md
- draft-js-mention-plugin/src/MentionSuggestions/index.js
When typing non-existing mention, empty dropdown open and up/down arrow catch by mention plugin. Cursor stick on  @non_exists_mention line.
Before:
After problem fixed:
> [mention] fix cursor not moving up/down on non existing mention

- draft-js-mention-plugin/src/MentionSuggestions/index.js
When trying to detect mention in differently styled text,  detection is not work. See demo.
We have more worse case with same reason of problem, in our project, where mention plugin is used. When adding mention in series: `@first_mention @second_mention` second mention is not detected.
In depth problem looks like:
1. From the portal detection decorated text is ` @second_mention` (started from space)
2. First ` `(space) goes in first leaf and `@second_mention` goes in second leaf.
3. Mention is not detected by regexp in `@second_mention` - no space here and it is not start at the begin of line.
Do not check leaves separately, use full decorated text to check.
Before:
After fix:
> [mention] fix mention detection in styled text

- draft-js-mention-plugin/src/mentionSuggestionsStyles.css
- draft-js-mention-plugin/src/utils/positionSuggestions.js
When typing @mention in the on of line, it goes to beginning of next line, but suggestion dropdown stays on the same vertical position and overlaps @mention text.
Calculate position of suggestion portal in relation of bottom (not top) decorated rectangle.
Before: 
After fix:
> [mention] fix suggestions dropdown position in case of line wrap

- draft-js-mention-plugin/CHANGELOG.md
- draft-js-mention-plugin/src/MentionSuggestions/Entry/defaultEntryComponent.js
I'm getting this warning `React does not recognize the 'isFocused' prop on a DOM element.`
Remove `isFocused ` from the passed props.
> [mention-plugin] Remove react warning

- draft-js-emoji-plugin/src/components/EmojiSelect/Popover/index.js
- draft-js-emoji-plugin/src/components/EmojiSelect/index.js
First of all thank you for the great plugins. 
While using `emoji select` page was loading very slow as it was making network requests to get all the images of the emojis of the `emoji select` popover. Now i am only rendering `emoji select popover` when user wants to see it. This way we are saving **1361** network requests for the images of emojis and hence making the page load time faster. 
This change will also come in handy when user is using multiple instances of emoji select. A normal example is comment boxes.
> Rendering emoji select popover only on emoji select button press

- draft-js-resizeable-plugin/CHANGELOG.md
- draft-js-resizeable-plugin/src/createDecorator.js
- draft-js-side-toolbar-plugin/CHANGELOG.md
- draft-js-side-toolbar-plugin/src/components/Toolbar/index.js
resolve #1021 #1023 #1024 #1039 
The ref attribute in draft-js-plugins-editor is no longer a string since [cf6653f196c0](https://github.com/draft-js-plugins/draft-js-plugins/commit/cf6653f196c0b23b191b03f968d30eace8e62d4b#diff-2180aea2d91b1762f617f66247191a4c)，so `.refs.editor` can not access the editor and cause subsequent errors.
Use `.editor` instead of `.refs.editor`.
> fixed refs for draft-js-resizeable-plugin and draft-js-side-toolbar-plugin

- draft-js-mention-plugin/src/MentionSuggestions/index.js
Hi,
I changed to warnings of `Immutable.List` are displayed only in the `process.env.NODE_ENV !== production` . Because not necessary in production.
> Warnings are displayed only in the not production

- docs/client/components/pages/Alignment/ThemedAlignmentEditor/alignmentToolStyles.css
- docs/client/components/pages/Alignment/ThemedAlignmentEditor/buttonStyles.css
- docs/client/components/pages/Alignment/ThemedAlignmentEditor/colorBlockPlugin.js
- docs/client/components/pages/Alignment/ThemedAlignmentEditor/editorStyles.css
- docs/client/components/pages/Alignment/ThemedAlignmentEditor/index.js
- docs/client/components/pages/Alignment/index.js
- draft-js-alignment-plugin/src/AlignmentTool/index.js
- draft-js-alignment-plugin/src/index.js
- stories/Alignment/ThemedAlignmentEditor/alignmentToolStyles.css
- stories/Alignment/ThemedAlignmentEditor/buttonStyles.css
- stories/Alignment/ThemedAlignmentEditor/colorBlockPlugin.js
- stories/Alignment/ThemedAlignmentEditor/editorStyles.css
- stories/Alignment/ThemedAlignmentEditor/index.js
- stories/index.js
Currently, I cannot customize `AlignmentTool` component, because styles are hard coded. 
I added `theme` object to customize `AlignmentTool`, like `InlineToolbar`.
I also added `ThemedAlignmentEditor` story.
[
](url)
> Add ability to customize AlignmentTool styles

- draft-js-plugins-editor/src/Editor/index.js
- draft-js-resizeable-plugin/CHANGELOG.md
- draft-js-resizeable-plugin/package.json
- draft-js-resizeable-plugin/src/createDecorator.js
fixes #1020 
disable default drag and drop if there is mouse-hover-position data (going to resize)
tested on Firefox 59.0.2 and Chrome 65.0.3325.181
> fixed image resizing bugs in Firefox

- draft-js-emoji-plugin/CHANGELOG.md
- draft-js-emoji-plugin/src/components/EmojiSuggestions/Entry/index.js
- draft-js-mention-plugin/CHANGELOG.md
- draft-js-mention-plugin/src/MentionSuggestions/Entry/index.js
First time submitting a PR to your repo, please let me know if I'm doing anything wrong 🙂 
Seems to me there's no changelog for the Mentions plugin, so just thought to summarize the changelog entry here:
- Add `aria-selected="true"` for the Mentions and Emojis listbox focused option.
- [ x] Fix any eslint errors that occur
- [ x] Enable "Allow edits from maintainers" for this PR
Based on the ARIA spec and the ARIA Authoring Practices, `aria-selected="true"` is a required ARIA state for the suggested option that is visually indicated as the currently selected option. For more details please refer to the related issue https://github.com/draft-js-plugins/draft-js-plugins/issues/1073
Just using the existing `isFocused` prop to render an `aria-selected="true"` attribute. Avoiding to render the …
> Mentions and Emoji: Use aria-selected for the focused listbox option

- draft-js-emoji-plugin/src/components/EmojiSuggestions/index.js
- draft-js-emoji-plugin/src/index.js
- draft-js-mention-plugin/src/MentionSuggestions/index.js
- draft-js-mention-plugin/src/index.js
- draft-js-plugins-editor/src/Editor/index.js
New to contributing to your repo, please let me know if I'm doing anything wrong 🙂
Seems to me there's no changelog for the Mentions plugin, so just thought to summarize the changelog entry here:
- Mentions and Emojis plugin: Pass the combobox `aria-expanded` values as boolean.
- [ x] Fix any eslint errors that occur
- [ x] Enable "Allow edits from maintainers" for this PR
`draft.js` has changed something since version 0.10.2 and now uses a pattern to make sure `aria-expanded` is only set when there's a `role="combobox"`. That's perfectly fine, but the actual pattern is the following one:
`var ariaExpanded = ariaRole === 'combobox' ? !!this.props.ariaExpanded : null;`
Thus, if a value is passed as string, it's always converted to boolean `true`. Actually, the `aria-expanded` value is …
> Mentions and Emojis: Pass the aria-expanded values as boolean.

- draft-js-emoji-plugin/CHANGELOG.md
- draft-js-emoji-plugin/src/components/EmojiSuggestions/Entry/index.js
- draft-js-mention-plugin/CHANGELOG.md
- draft-js-mention-plugin/src/MentionSuggestions/Entry/index.js
To make screen readers able to read out the options in the Mentions and Emojis suggestions list, each option should have an `id` attribute that can be referenced by `aria-activedescendant` used on the textarea. See https://www.w3.org/TR/wai-aria-1.1/#aria-activedescendant
> For example, in a combobox, focus may remain on the textbox while the value of aria-activedescendant on the textbox element refers to a descendant of a popup listbox that is controlled by the textbox.
Everything is already in place, the ID value to use is available. There's just the need to pass the `id` prop. I've tested this on Windows, with various browsers / screen readers combinations:
Firefox ESR + NVDA 2018.1.1
Firefox 59.0.2 + NVDA 2018.1.1 
IE 11 + NVDA 2018.1.1
IE 11 + JAWS 2018
(Note: current Firefox 59 has …
> Mentions and Emojis: Add IDs to the combobox listbox options

- draft-js-undo-plugin/CHANGELOG.md
- draft-js-undo-plugin/package.json
- draft-js-undo-plugin/src/RedoButton/__test__/index.js
- draft-js-undo-plugin/src/RedoButton/index.js
- draft-js-undo-plugin/src/UndoButton/__test__/index.js
- draft-js-undo-plugin/src/UndoButton/index.js
the redo/undo button not working #1139 
use `stopPropagation` to avoid trigger focus
> draft-js-undo-plugin: fix issue about button not working when it have the same parent container with editor

- draft-js-image-plugin/CHANGELOG.md
- draft-js-image-plugin/package.json
- draft-js-image-plugin/src/index.js
See https://github.com/draft-js-plugins/draft-js-plugins/issues/1171
This will match on both the old `image` and new `IMAGE` entity types.
> Support old lower-case entity type `image` for backwards compatibility

- draft-js-emoji-plugin/CHANGELOG.md
- draft-js-emoji-plugin/src/components/EmojiSelect/Popover/Groups/Group/index.js
- draft-js-emoji-plugin/src/components/EmojiSelect/Popover/Groups/index.js
- draft-js-emoji-plugin/src/components/EmojiSelect/Popover/index.js
This is an update of https://github.com/draft-js-plugins/draft-js-plugins/pull/1030 PR which never got merged.
So currently emoji plugin loads 1.3k emojis initially, which is just insane.
With this change it initially loads only 225 (first emoji group), then after the emoji popup is opened - second group of emojis loads. When user navigates to other groups it lazy loads current viewed group + next group to give best user experience. So if user doesn't scroll very fast his currently viewed group should be always loaded.
I know there was discussion in  https://github.com/draft-js-plugins/draft-js-plugins/pull/1030 about checking if image loaded with `onLoad` and only then preventing re-rendering of a group. But to me this seems not related to issue of lazy loading. Current implementation …
> [emoji-plugin] lazy load emojis

- draft-js-alignment-plugin/CHANGELOG.md
- draft-js-alignment-plugin/package.json
- draft-js-alignment-plugin/src/index.js
- draft-js-resizeable-plugin/CHANGELOG.md
- draft-js-resizeable-plugin/package.json
- draft-js-resizeable-plugin/src/index.js
When using multiple alignment tools at the same time, even when I took care to create new instances of each plugin, I would see the alignment and focus be shared among the other editors. 
#1176 
I simply moved the store creation into the functions that create the plugins. 
> Fixing plugins with stores outside of the create plugin functions

- draft-js-side-toolbar-plugin/src/components/BlockTypeSelect/index.js
Just discovered this; seems like a bug. If you click the button, the editor loses focus right now. This will be fixed after this PR.
I changed it into what seems to be the original intention of the file author.
> Fixed: onMouseDown called onClick

- draft-js-mention-plugin/CHANGELOG.md
- draft-js-mention-plugin/package.json
- draft-js-mention-plugin/src/mentionSuggestionsStrategy.js
- draft-js-mention-plugin/src/utils/__test__/getSearchTextAt.js
- draft-js-mention-plugin/src/utils/getSearchTextAt.js
1. replacing behavior is wrong while mentionTrigger is empty
2. page got infinite loop when mentionTrigger is empty and supportWhiteSpace is true
The infinite loop was cause by the update issue about regex's lastIndex, i just add a force update in it.
> fix(mention-plugin): avoid infinite loop while mentionTrigger is empty with supportWhiteSpace

- README.md
Accordingly the documentation for the hashtag plugin, the linkifyPlugin should be listed before the hashtag to avoid problems.
> Updating documentation plugin order

- HOW_TO_CREATE_A_PLUGIN.md
- draft-js-emoji-plugin/CHANGELOG.md
- draft-js-emoji-plugin/src/components/EmojiSuggestions/index.js
- draft-js-emoji-plugin/src/index.js
- draft-js-focus-plugin/CHANGELOG.md
- draft-js-focus-plugin/src/index.js
- draft-js-mention-plugin/CHANGELOG.md
- draft-js-mention-plugin/src/MentionSuggestions/__test__/index.js
- draft-js-mention-plugin/src/MentionSuggestions/index.js
- draft-js-mention-plugin/src/index.js
- package.json
All onDownArrow, onUpArrow, onLeftArrow, onRightArrow, onEscape, onTab
usages are replaced with keyBindingFn.
Their mentions are dropped from HOW_TO_CREATE_A_PLUGIN tut.
> Remove deprecated draft-js hooks usage

- scripts/build-css.js
Classnames are generated from paths, index and displayName.
In this diff I fixed the problem of passing different paths by linaria
babel plugin and cli.
> Fix linaria classnames

- draft-js-hashtag-plugin/src/Hashtag/index.js
fixes https://github.com/draft-js-plugins/draft-js-plugins/issues/1342
inside this file `draft-js-plugins/draft-js-hashtag-plugin/src/Hashtag/index.js`
I declared the "blockKey" property to make sure it does not compare inside the `otherProps` object, containing the undeclared component props.
This way the "blockKey" property will not be applied to a `span` element, thus avoid triggering the warning.
```
"React does not recognize the `blockKey` prop on a DOM element"
```
> removes `blockKey` prop incorrectly applied on a DOM element

- draft-js-static-toolbar-plugin/package.json
- draft-js-static-toolbar-plugin/src/index.d.ts
Add typescript typing for the Static Toolbar plugin.
Ref. Inline Toolbar plugin. https://github.com/draft-js-plugins/draft-js-plugins/pull/1290
> Add Static Toolbar Typing

- draft-js-resizeable-plugin/src/createDecorator.js
The same issue that was described in [#926](https://github.com/draft-js-plugins/draft-js-plugins/issues/926), but in a different plugin. In some cases a re-render happens earlier than initialization, which causes store.getReadOnly to be undefined, so calling it results in an error.
Check whether store.getReadOnly is defined first, and only call it if it is.
If it isn't defined, assume that it's read only.
> check whether getReadOnly is undefined

- draft-js-plugins-editor/src/Editor/index.js
I'm trying read whether the editor is in readOnly mode or not (from my plugin). But I can't do it since all I can read is whether I've given a `readOnly` prop or not. But readOnly is a state field. I can't reach it this way. 
This way to do it is just fine: 
```js
getReadOnly = () => this.props.readOnly || this.state.readOnly;
```
> fix getreadonly problem

- HOW_TO_CREATE_A_PLUGIN.md
Draft.js documentation links changed and the links in HOW_TO_CREATE_A_PLUGIN are no longer pointing to the correct resources.
These changes should make it work again.
> Update links to Draft.js documentation

- draft-js-resizeable-plugin/CHANGELOG.md
- draft-js-resizeable-plugin/README.md
- draft-js-resizeable-plugin/src/createDecorator.js
- draft-js-resizeable-plugin/src/index.d.ts
Implements an option to set the initial height and initial width of the resized content **without breaking changes**.
Closes [#1166](https://github.com/draft-js-plugins/draft-js-plugins/issues/1166).
When horizontal or vertical properties are "relative" or "absolute", the default value is 40 (40% or 40px, depending whether "relative" or "absolute" is set). Currently, it is not possible to change default value. For example, if I want the block width to be absolute, without affecting initial width, it is not possible to do so.
You can pass optional two parameters: `initialWidth` and `initialHeight` to the first argument of `createResizeablePlugin` and change the default style of width and/or height. Typescript declaration is also updated.
```js
const resizePlugin = createResizeablePlugin({ …
```
> add support of initialWidth & initialHeight

- draft-js-plugins-editor/src/Editor/index.js
getReadOnly only returns props.readOnly and not the this.state.readOnly.
e.g. This updates the state and not props.readOnly
setReadOnly = readOnly => {
if (readOnly !== this.state.readOnly) this.setState({ readOnly });
};
If you're implementing or changing a feature, please add a gif to demo the change, …
> Return this.state.readOnly too in getReadOnly()

- draft-js-side-toolbar-plugin/CHANGELOG.md
- draft-js-side-toolbar-plugin/package.json
- draft-js-side-toolbar-plugin/src/index.d.ts
Not able to use this plugin within a TypeScript project
Added `index.d.ts` file with a definition of each part of the plugin
> Added typescript definitions for SideToolbar plugin

- draft-js-plugins-editor/src/index.d.ts
Currently users cannot extend the editor with custom key commands if they are using typescript. 
This change adds a  union with string to the DraftEditorCommand. So users can do things like return a command 'save' for `cmd/ctrl + s`.
An alternative implementation is to declare an EditorCommand type. `type EditorCommand = …
> Allow for Custom Key Commands in Types

- draft-js-plugins-editor/CHANGELOG.md
- draft-js-plugins-editor/src/Editor/index.js
Apply decorators and set selection after initial rendering to prevent `onChange` to trigger during the render cycle, as this now results in ["Warning: Cannot update a component from inside the function body of a different component."](https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-some-updates-during-render). 
**The problem**
Many people will have the `onChange` callback hooked up to some state setter on the editor, i.e.
```javascript
const [editorState, setEditorState] = useState(..);
return <Editor onChange={(newEditorState) => setEditorState(newEditorState)} editorState={editorState} />
```
As `onChange` is called during rendering [in the Editor](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L74), when …
> #1393 Apply decorators and set the selection after rendering

- draft-js-mention-plugin/src/defaultRegExp.js
add vietnamese trigger for mention plugin.
Characters are listed in here: http://vietunicode.sourceforge.net/charset/
Thank you :)
> [draft-js-mention-plugin] add support for vietnamese characters

- draft-js-mention-plugin/src/MentionSuggestions/MentionSuggestions.js
Open suggestions without leading space or character after mention trigger (when support for whitespace is enabled).
Change duplicated with: https://github.com/draft-js-plugins/draft-js-plugins/pull/1374
> Suggestions trigger rule

- package.json
- scripts/build-css.js
- yarn.lock
See Ticket #1562
Updates to linaria 2.0.2 with the bugfix https://github.com/callstack/linaria/issues/698, adjust `scripts/build-css.js` to resolve `ts/tsx` files
> Fixing building of css

- packages/alignment/package.json
- packages/anchor/package.json
- packages/buttons/package.json
- packages/counter/package.json
- packages/divider/package.json
- packages/drag-n-drop-upload/package.json
- packages/drag-n-drop/package.json
- packages/editor/package.json
- packages/emoji/package.json
- packages/focus/package.json
- packages/hashtag/package.json
- packages/image/package.json
- packages/inline-toolbar/package.json
- packages/linkify/package.json
- packages/mention/package.json
- packages/resizeable/package.json
- packages/side-toolbar/package.json
- packages/static-toolbar/package.json
- packages/sticker/package.json
- packages/undo/package.json
- packages/utils/package.json
- packages/video/package.json
A new release currently exit with the following error
```
error parsing json: {ts,tsx}' -o /home/runner/work/draft-js-plugins/draft-js-plugins/packages/mention/lib-css
Successfully extracted 1 CSS files.
{
```
I removed the build step in prebuild as there is already a full build.
> Remove build in prepublish

- package.json
- packages/emoji/package.json
- packages/emoji/src/constants/defaultEmojiGroups.tsx
- yarn.lock
Currently the type definition for `react-icons` are broken
This PR pushes `react-icons` to 3.11.0 to match the previous update `@types/react-icons`.
> Update to react icons 3

- packages/editor/CHANGELOG.md
- packages/editor/src/Editor/index.tsx
Fixes [#1393](https://github.com/draft-js-plugins/draft-js-plugins/issues/1393)
> Change UNSAFE_componentWillReceiveProps to componentDidUpdate; fix #warnings-for-some-updates-during-render

- packages/editor/package.json
- packages/emoji/package.json
- packages/emoji/src/components/EmojiSuggestions/index.tsx
The `EmojiSuggestions` parameter should be optional. Also `@draft-js-plugins/utils` are missing as a dependency.
This PR fixes the issues and bump a new version.
> Fixing typescript definitions for emoji plugin

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
Currently there is only one template for questions, feature requests and bugs. Also it would be better if questions are asked in the slack channel as it may be hard to find the link.
This PR add new templates which should also add tags. A link to Slack should be provided.
> Improve issue templates

- packages/emoji/package.json
- packages/emoji/src/components/EmojiSuggestions/index.tsx
- packages/emoji/src/components/EmojiSuggestionsPortal/index.tsx
- packages/emoji/src/index.tsx
Currently I have the following warning on opening my page:
```
Warning: Cannot update a component from inside the function body of a different component.
in EmojiSuggestionsPortal (created by DecoratedEmojiSuggestionsPortal)
in DecoratedEmojiSuggestionsPortal (created by DecoratedComponent)
in DecoratedComponent (created by DraftEditorBlock)
in div (created by DraftEditorBlock)
in DraftEditorBlock (created by DraftEditorContents)
in div (created by DraftEditorContents)
in div (created by DraftEditorContents)
in DraftEditorContents (created by DraftEditor)
...
| onChange | @ | Editor.tsx:113
  | PluginEditor._this.onChange | @ | index.esm.js:462
  | UNSAFE_componentWillMount | @ | index.esm.js:756
...
```
Where `UNSAFE_componentWillMount | @ | index.esm.js:756` resolves to: …
> Fixing react warning from emoji plugin

- packages/docs/pages/plugin/emoji/index.js
- packages/emoji/CHANGELOG.md
- packages/emoji/src/components/EmojiSelect/Popover/Groups/index.tsx
- packages/emoji/src/components/EmojiSelect/Popover/index.tsx
- packages/emoji/src/theme.ts
See Issue #1635
This PR removes the `onWheel` event listener and replaces it with the css property `overscroll-behavior: contain;`
> Fixing warning on scrolling in emoji select #1635

- packages/editor/package.json
- packages/editor/src/Editor/index.tsx
- packages/mention/package.json
- packages/mention/src/index.tsx
`@draft-js-plugins/mention`  `keyBindingFn` returns `null` if `callbacks.keyBindingFn` is not defined which breaks the chain of the `keyBindingFn` of other plugins. See also #1601.
`@draft-js-plugins/mention`  `keyBindingFn` returns now undefined if `callbacks.keyBindingFn` is not defined. Also fixed the type definition for `@draft-js-plugins/editor` `keyBindingFn` as mentioned in #1651
> Fixing keyBindingFn in mention plugin

- packages/buttons/CHANGELOG.md
- packages/buttons/src/index.ts
in v3, I use to be able to access the `createBlockAlignmentButton` util even though it wasn't publicly exposed, but now it is written in typescript thus this is now necessary
```js
// before
import createBlockAlignmentButton from 'draft-js-buttons/lib/utils/createBlockAlignmentButton';
```
exposing util to make it public
```js
// now
import { createBlockAlignmentButton } from '@draft-js-plugins/buttons'
```
> chore: expose createBlockAlignmentButton in buttons package

- packages/drag-n-drop/package.json
- packages/editor/package.json
- packages/emoji/package.json
- packages/focus/package.json
- packages/mention/package.json
- packages/sticker/package.json
- yarn.lock
Reverts draft-js-plugins/draft-js-plugins#1531
Draft-js still depends on "~3.7.4" which makes production bundle quite bloated with immutable.js instances. Only yarn resolution would help.
> Revert "chore(deps): bump immutable from 3.7.6 to 3.8.2"

- packages/mention/CHANGELOG.md
- packages/mention/package.json
- packages/mention/src/index.tsx
See issue #1736 
This PR removes the undocumented plugin config option `entryComponent`. The config had overwritten the `entryComponent` option the `MentionSuggestion` component.
> [Mention Plugin] Remove entryComponent from plugin config

- packages/anchor/CHANGELOG.md
- packages/anchor/package.json
- packages/anchor/src/components/DefaultLinkButton.tsx
- packages/anchor/src/components/LinkButton.tsx
- packages/anchor/src/index.tsx
- packages/docs/pages/plugin/anchor/index.js
Currently the link button is not customizable with a fixed SVG icon.
I added a optional `LinkButton` property to the plugin config to set a custom component for rendering.
> [Anchor Plugin] make link button customizable

- packages/docs/pages/plugin/emoji/index.js
- packages/emoji/CHANGELOG.md
- packages/emoji/src/components/EmojiSelect/index.tsx
This one closes #1580
Some users desired onOpen and onClose props to be thrown to EmojiSelect
added callback props to be called upon closing and opening of the popover
> add onOpen and onClose callback props to EmojiSelect

- packages/mention/src/MentionSuggestionsPortal.tsx
in the draftjs  when compositionEnd, it will force re-render, and all the block will unmount, and mount
when useEffect, we will get old state, and using old state to setState, it cause the bug.
https://github.com/facebook/draft-js/blob/master/src/component/handlers/composition/DraftEditorCompositionHandler.js#L242 …
> fixing mention composition

- packages/docs/next.config.js
- packages/docs/package.json
- yarn.lock
next.js currently throws the following error on build:
```
> Build error occurred
/home/hcomuser/dev/rr/draft-js-plugins/node_modules/lodash-es/escapeRegExp.js:1
import toString from './toString.js';
^^^^^^
```
This PR transpiles the `lodash-es` package.
> Fixing transpile issue for nextjs

- packages/alignment/src/createDecorator.tsx
- packages/docs/components/Examples/alignment/SimpleAlignmentEditor/editorStyles.module.css
- packages/docs/components/Examples/alignment/SimpleAlignmentEditor/index.js
- packages/docs/components/Examples/alignment/ThemedAlignmentEditor/editorStyles.module.css
- packages/docs/components/Examples/alignment/ThemedAlignmentEditor/index.js
- stories/alignment/src/SimpleAlignmentEditor.tsx
- stories/alignment/src/editorStyles.css
closes #1605
This PR moves the color block above the text line which prevent the selection of the color block.
> [Alignment Plugin] add wrapper for color block

- .eslintrc.js
- packages/docs/next-env.d.ts
- packages/docs/pages/plugin/mention/index.tsx
- packages/docs/pages/plugin/side-toolbar/index.js
- packages/side-toolbar/CHANGELOG.md
- packages/side-toolbar/src/components/BlockTypeSelect/SideToolbarButton.tsx
- packages/side-toolbar/src/components/BlockTypeSelect/index.tsx
- packages/side-toolbar/src/components/Toolbar/index.tsx
- packages/side-toolbar/src/index.tsx
Adds the `sideToolbarButtonComponent` option to customize the sidebar button.
closes #2179
> [Side Toolbar Plugin] add option to customize button

- packages/mention/CHANGELOG.md
- packages/mention/package.json
- packages/mention/src/MentionSuggestions/Entry/Entry.tsx
delays the scroll into view for the selected mention list item as the popup takes some time for positioning.
closes #2233
> [Mention Plugin] delay scrolling into view

- packages/alignment/CHANGELOG.md
- packages/alignment/package.json
- packages/alignment/src/createDecorator.tsx
> [Alignment Plugin] Set visibleBlock to null on decorator destructing

- .storybook/main.js
- packages/anchor/package.json
- packages/docs/package.json
- yarn.lock
fixing the next.js build error:
```
ModuleNotFoundError: Module not found: Error: ESM packages (prepend-http) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals
```
> Downgrade prepend-http to 3.0.1

- packages/mention/src/modifiers/addMention.ts
When inserting a mention, the current inline styles should be applied to the text (for instance font size, font family and text decoration) rather than only the default styles of the mention.
> Use current inline style for mention

- packages/docs/components/Examples/mention/CustomMentionEditor/Mentions.ts
- packages/mention/CHANGELOG.md
- packages/mention/src/defaultRegExp.ts
Some characters are not supported by mention plugin.
These may be used for Japanese personal names.
In particular, `々 (\u3005)` is commonly used.
Add characters to regExp.
https://user-images.githubusercontent.com/233012/147100271-52a991f3-ebab-4a1f-8101-2f62c6088ae3.mp4
> Add Japanese symbol to default regExp

- packages/docs/pages/plugin/emoji/index.js
Noticed a small typo in the documentation for the `emoji` plugin.
> Fix typo in docs

- README.md
> Missing plugins shown on /plugin docs page

- packages/editor/CHANGELOG.md
- packages/editor/package.json
- packages/editor/src/Editor/index.tsx
Using `EditorState.moveSelectionToEnd` instead of  `EditorState.moveFocusToEnd`
closes #2521, #2586
> [Editor] fixing setting focus

- packages/emoji/CHANGELOG.md
- packages/emoji/package.json
- packages/emoji/src/utils/createEmojisFromStrategy.ts
escaping variation selector-16 character when splitting emojis into categories
Before: 
After (+8 hand gesture emojis here):
> Remove all non printable characters from emojibase data

- packages/mention/CHANGELOG.md
- packages/mention/package.json
- packages/mention/src/index.tsx
- stories/mentions-custom-container-component/src/CustomComponentMentionEditor.stories.tsx
- stories/mentions-custom-container-component/src/CustomContainerComponentMentionEditor.tsx
- stories/mentions-custom-container-component/src/editorStyles.css
- stories/mentions-custom-container-component/src/mentions.ts
When you want to overwrite the MentionSuggestions container with a custom style you lose Popper.js functionally which in some cases you want to overwrite the container only for styling without losing Popper.js functionally.
for that manner, you could wrap your container with a Popper component which will handle that for you.
Popper component currently privet, exporting that component will enable this feature.
Export Popover component for custom container usage without losing Popper functionally
```
<MentionSuggestions
popoverContainer={({children, ...props}) => (
<Popover {...props}>
<div style={{ background: '#000', color: '#fff' }}>
{children}
</div>
</Popover>
)}
/>
```
> feat: export Popover component for custom container usage without losing Popper functionally

- .github/workflows/dependabot-auto-merge.yml
- .github/workflows/deployWebsite.yml
- .github/workflows/tests.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> Set permissions for GitHub actions

- packages/inline-toolbar/CHANGELOG.md
- packages/inline-toolbar/package.json
- packages/inline-toolbar/src/components/Toolbar/index.tsx
If an ancestor of DraftEditor-root has a max height and overflow: auto set, we don't position the inline toolbar correctly because we don't account for scrollTop on ancestor nodes. As a result, the toolbar can appear far down the screen and even off page in these scenarios.
Aggregate scrollTop on all ancestor nodes and include it in positioning calculation for the inline toolbar.
> Inline toolbar plugin should account for ancestor scrollTop

- CONTRIBUTING.md
The CONTRIBUTING.md contribution setup steps are insufficient to
being contributing.
Upon first pull of the repository, the steps specified in
CONTRIBUTING.md to get started were not enough to actually
load the `docs` package and begin hacking away. This updates
those steps to bring the documentation up to snuff.
> Improve CONTRIBUTING.md for first-time steps

- package.json
- packages/buttons/CHANGELOG.md
- packages/buttons/package.json
- packages/buttons/src/utils/createBlockAlignmentButton.tsx
- packages/buttons/src/utils/createBlockStyleButton.tsx
- packages/buttons/src/utils/createInlineStyleButton.tsx
- packages/buttons/src/utils/createTextAlignmentButton.tsx
Accessibility matters and is increasingly relevant as more of the world moves online. The plugins were not labeled in a way screen readers could interpret, and this has a negative impact on accessibility. Applications using these plugin buttons were inaccessible by default without labels provided, as they cannot be applied at the component level without being rendered through JSX into the final parsed HTML on the actual DOM. 
See: 
- [React Accessibility](https://reactjs.org/docs/accessibility.html)
- [WCAG Accessibility Standards](http://web-accessibility.carnegiemuseums.org/foundations/aria/)
Added button-type specific aria roles and aria labels to the plugin buttons via their generator functions. 
Not necessary.
> Resolves current accessibility issues - Aria roles and labels to buttons

- packages/emoji/CHANGELOG.md
- packages/emoji/package.json
- packages/emoji/src/components/EmojiSelect/index.tsx
When using multiple emoji picker plugins on one page (imagine a list of posts like fb timeline that each have its own comment input and emoji picker button) there is an issue that already open emoji picker popover want close if you click on another instances popover trigger button.
The issue can be seen on demo page of emoji plugin https://www.draft-js-plugins.com/plugin/emoji
As can be seen, in the change I have updated the event listener on the document to call a specific function `closeIfClickedOutside` which is simply checking if the click target element is something inside emoji popover component or no. …
> Autoclose emoji popover for multiple instance

- packages/emoji/CHANGELOG.md
- packages/emoji/package.json
- packages/emoji/src/components/EmojiSelect/Popover/Entry/index.tsx
- packages/emoji/src/components/EmojiSuggestions/Entry/index.tsx
- packages/emoji/src/modifiers/addEmoji.ts
- packages/emoji/src/utils/__test__/shortnameToUnicode.test.ts
- packages/emoji/src/utils/shortnameToUnicode.ts
Opening the Emoji Select or the Emoji Suggestion for the first time is extremely slow, ca. 3 seconds.
Subsequent usage is fast though.
The reason for that is, that `shortnameToUnicode` (from the `emoji-toolkit` library) uses a really huge RegEx, which is slow for the first call.
Instead of using this library method, we create a mapping from shortname to unicode from the same data used to build the EmojiStrategy.
> Speed up initial opening of select

- packages/drag-n-drop-upload/CHANGELOG.md
- packages/drag-n-drop-upload/package.json
- packages/drag-n-drop-upload/src/components/insertPlaceholder.ts
This PR fixes a known bug #2849, the fix uses a more dynamic method to pick the right inserted block-key which is used in order to remove the upload-placeholder...
in the previous version the InsertPlaceholder function just picks statically the second-last block which results in wrong block-key for deletion.
I just removed this method and replaced it a dynamic method by reading the inserted atomic block after the creation using the `getSelection().getAnchorKey()`.
> fix: Upload placeholder does not get removed after finish upload #2849

- packages/anchor/CHANGELOG.md
- packages/anchor/package.json
- packages/anchor/src/components/DefaultLinkButton.tsx
LinkButton component lacked an accessibility label. It was out of WCAG compliance and recent PR's have upgraded other RichText Draft.js plugin buttons to add accessibility labeling via aria-label. This means users who are visually disabled or navigate with screen readers are unable to fully utilize the functionality of this button and have a challenging experience.
React accepts a prop 'aria-label' in JSX that will result in an HTML 'aria-label'. An aria-label prop of "create hypertext link" was added so the rendered HTML button has the same aria-label, meets accessibility guidelines, and is not problematic for users navigating with screen readers. See WCAG guidelines: [WCAG label …
> Improve Accessibility for LinkButton with appropriate descriptive Aria Label

- packages/emoji/CHANGELOG.md
- packages/emoji/package.json
- packages/emoji/src/utils/__test__/shortnameToUnicode.test.ts
- packages/emoji/src/utils/shortnameToUnicode.ts
There are some emojis missing in 'emojibase-data' library which are present in 'emoji-toolkit' library. adding these emojis leads to undefined. There is an existing function in 'emoji-toolkit' library to get unicode from the shortName so I have used that function in case emojis not found in the existing map.
> add missing emojie

- packages/emoji/CHANGELOG.md
- packages/emoji/package.json
- packages/emoji/src/utils/__test__/shortnameToUnicode.test.ts
- packages/emoji/src/utils/shortnameToUnicode.ts
Somehow, `shortnameToUnicode` was not finding all the shortcodes and was using `shortnameToUnicode` from emoji-toolkit, which is using a very slow regex.
Now it's very much faster 💯 
Some `toShort(item.unicode)` are UTF-16 encoded strings, while `str` is UTF-8. So I use `localeCompare` to compare this correctly.
Also, `mapShortnameToUnicode` was not including skins.
> improve `shortnameToUnicode` performance not using `emoji-toolkit` function anymore

- packages/emoji/CHANGELOG.md
- packages/emoji/package.json
- packages/emoji/src/__test__/EmojiSelect.test.tsx
- packages/emoji/src/components/EmojiSelect/Popover/Entry/index.tsx
- packages/emoji/src/components/EmojiSelect/index.tsx
- packages/emoji/src/theme.ts
Issue [#3233](https://github.com/draft-js-plugins/draft-js-plugins/issues/3233)
The emoji plugin lacks keyboard navigation ability
This creates the appropriate styles and keyboard handlers to allow the EmojiSelect menu to be navigable via keyboard.
After:
https://github.com/draft-js-plugins/draft-js-plugins/assets/11545784/3eab1edd-a776-4c9b-a11a-4c6d645a8ed2
> Improve emoji keyboard navigability

- packages/docs/pages/plugin/emoji/index.js
- packages/emoji/CHANGELOG.md
- packages/emoji/package.json
- packages/emoji/src/__test__/EmojiSelect.test.tsx
- packages/emoji/src/components/EmojiSuggestions/Popover.tsx
- packages/emoji/src/components/EmojiSuggestions/index.tsx
- packages/emoji/src/components/EmojiSuggestionsPortal/index.tsx
- packages/emoji/src/index.tsx
- packages/emoji/src/theme.ts
- packages/emoji/src/utils/warning.ts
Issue #3254
The emoji plugins suggestions popover can overflow the viewport when it pops up near the bottom.
This follows the precedent set in the `mention` plugin, and follows that example by using [popper.js](https://popper.js.org/docs/v2/) to implement the popover. It also deprecates the `positionSuggestions` prop and introduces `popperOptions`, again trying to align with the example set in the mention plugin (PR #2029).
After:
> Improve emoji popover positioning
