src/components/Editor/Sticker/index.js, src/components/Editor/Sticker/styles.js
=> Better remove button

src/components/Editor/Sticker/index.js, src/components/Editor/Sticker/styles.js, src/components/Editor/constants/stickers.js, src/components/Editor/index.js
=> Make stickers list immutable

site/components/UnicornEditor/index.js, site/webpack.config.js, src/linkPlugin/Link/index.js, src/linkPlugin/Link/styles.js, src/linkPlugin/findWithRegex.js, src/linkPlugin/index.js, src/linkPlugin/linkStrategy.js
I figured I should try and see how easy it is to write a plugin – turns out quite easy, especially since this isn't radically different from the hashtagPlugin! 
It's not perfect yet, but it works for now. The regex is bad and it doesn't actually link to it in the editor, but it works!
Ref #18
=> First link plugin implementation

site/components/CodeHighlight/index.js, site/components/StatePreview/index.js, site/css/prism.css, site/index.html, site/package.json, site/server.js
For some reason, this isn't working just yet, but I've been banging my head against it for too long – does one of you see the mistake by chance?
=> WIP code highlighting

package.json
Replaced 'unicorn-editor' with 'draft-js-plugin-editor'
=> package.json: Fixed project name

site/components/UnicornEditor/index.js, site/webpack.config.js, src/historyPlugin/Button/index.js, src/historyPlugin/Button/styles.js, src/historyPlugin/README.md, src/historyPlugin/RedoButton/index.js, src/historyPlugin/UndoButton/index.js, src/historyPlugin/index.js
This plugin exports an undo and redo button that allow you to add undo/redo functionality to the editor.
Ref #17
=> Add historyPlugin

README.md
Made it clear in the README that Node.JS v5 is required.
=> Added required node version to README.

README.md, docs/client/components/pages/Home/styles.css
=> Minor docs fixes

draft-js-emoji-plugin/src/Emoji/index.js
=> Add missing ImmutableJS Map import

docs/client/components/pages/Emoji/CustomEmojiEditor/emojiStyles.css, docs/client/components/pages/Emoji/CustomEmojiEditor/index.js, docs/client/components/pages/Emoji/SimpleEmojiEditor/index.js, docs/client/components/pages/Emoji/gettingStarted.js, docs/client/components/pages/Emoji/index.js, docs/client/components/pages/Hashtag/CustomHashtagEditor/index.js, docs/client/components/pages/Hashtag/gettingStarted.js, docs/client/components/pages/Hashtag/index.js, docs/client/components/pages/Home/UnicornEditor/index.js, docs/client/components/pages/Home/index.js, docs/client/components/pages/Linkify/gettingStarted.js, docs/client/components/pages/Linkify/index.js, docs/client/components/pages/Mention/gettingStarted.js, docs/client/components/pages/Mention/index.js, docs/client/components/pages/Sticker/gettingStarted.js, docs/client/components/pages/Sticker/index.js, docs/client/components/pages/Undo/gettingStarted.js, docs/client/components/pages/Undo/index.js, docs/client/components/shared/Code/index.js, docs/client/components/shared/FacebookButton/index.js, docs/client/components/shared/GithubButton/index.js, docs/webpack.config.dev.js, docs/webpack.config.prod.js, draft-js-linkify-plugin/src/Link/index.js, draft-js-mention-plugin/src/MentionSearch/index.js, draft-js-mention-plugin/src/modifiers/addMention.js, draft-js-mention-plugin/src/utils/__test__/getWordAt.js, draft-js-sticker-plugin/src/modifiers/addSticker.js, draft-js-sticker-plugin/src/modifiers/removeSticker.js, draft-js-undo-plugin/README.md
There are a lot of minor changes here, so please feel free to pick and choose! ([...ahem](https://twitter.com/clattner_llvm/status/673048357602902017))
=> Fix various typos and update copy

docs/client/components/pages/Home/index.js
=> proper nesting for all team members

draft-js-emoji-plugin/package.json, draft-js-emoji-plugin/webpack.config.js, draft-js-hashtag-plugin/package.json, draft-js-hashtag-plugin/webpack.config.js, draft-js-linkify-plugin/package.json, draft-js-linkify-plugin/webpack.config.js, draft-js-mention-plugin/package.json, draft-js-mention-plugin/webpack.config.js, draft-js-sticker-plugin/package.json, draft-js-sticker-plugin/webpack.config.js, draft-js-undo-plugin/package.json, draft-js-undo-plugin/webpack.config.js, package.json
Since we have CSSModules in there we needed a Webpack export to make it work well for everyone.
=> Proper lib compilation

draft-js-emoji-plugin/README.md, draft-js-hashtag-plugin/README.md, draft-js-linkify-plugin/README.md, draft-js-mention-plugin/README.md, draft-js-sticker-plugin/README.md, draft-js-undo-plugin/README.md
Just adding more instructions to help people know exactly how to import CSS via webpack.
=> Create detailed Webpack instruction to import CSS

draft-js-dnd-plugin/src/blockRendererFn.js, draft-js-dnd-plugin/src/index.js, draft-js-dnd-plugin/src/modifiers/refreshEditorState.js, draft-js-plugins-editor/src/Editor/index.js
As requested in https://github.com/draft-js-plugins/draft-js-plugins/issues/156
For now, it might not be necessary. We can reevaluate something like that as soon as I see no other reasonable way around it.
=> Remove inject block props

draft-js-emoji-plugin/src/modifiers/addEmoji.js
Refactored the variable names and comments as it probably was forgotten when copying code from addMention.
(I'm new to making PR's, so any feedback to improve is really appreciated.)
=> refactor addEmoji modifier

docs/client/components/pages/Linkify/CustomLinkifyEditor/index.js, docs/client/components/pages/Linkify/SimpleLinkifyEditor/index.js, docs/client/components/pages/Linkify/index.js, draft-js-linkify-plugin/CHANGELOG.md, draft-js-linkify-plugin/README.md, draft-js-linkify-plugin/src/Link/__test__/index.js, draft-js-linkify-plugin/src/Link/index.js, draft-js-linkify-plugin/src/index.js
=> Adding ability to set prefix and target for Linkify plugin

package.json
=> Make it actually work

draft-js-plugins-editor/src/Editor/index.js
only needs to call `createEventHooks` or `createFnHooks` once for the given `attrName` ?
=> createPluginHooks improvements

package.json
Please test. Not sure if flow is running.
=> Added lint-staged. Closes #178

draft-js-plugins-editor/src/Editor/__test__/index.js, draft-js-plugins-editor/src/Editor/createCompositeDecorator.js, draft-js-plugins-editor/src/Editor/index.js, testHelper.js
=> Adding `decorators` props on PluginEditor (and specs)

draft-js-plugins-editor/src/Editor/__test__/index.js, draft-js-plugins-editor/src/Editor/index.js
Added support for customStyleMap as a prop on the Editor itself + spec
=> Added customStyleMap

draft-js-emoji-plugin/src/emojiStyles.css, draft-js-emoji-plugin/src/index.js, draft-js-emoji-plugin/src/modifiers/addEmoji.js
fixed #111, contain emojis via css and added immutable entity
cc @nikgraf
=> Make emojis immutable entities, contain with css

draft-js-counter-plugin/package.json, draft-js-counter-plugin/src/CharCounter/__test__/index.js, draft-js-counter-plugin/src/CharCounter/index.js, draft-js-counter-plugin/src/LineCounter/__test__/index.js, draft-js-counter-plugin/src/WordCounter/__test__/index.js, draft-js-counter-plugin/src/WordCounter/index.js
@nikgraf I've made the changes you specified before. Unfortunately, it's been a bit busy so I haven't gotten around to the documentation stuff yet:
> Description
Getting Started + Hint about CSS
Configuration Parameters
Simple Example
Custom Example (with a custom theme)
I know you wanted to release 1.0.0 this weekend, but unfortunately I'm not sure if I'll have time to do all that before Monday. Sorry for the tardiness.
=> Counter plugin

draft-js-emoji-plugin/src/emojiStrategy.js, draft-js-emoji-plugin/src/index.js, draft-js-emoji-plugin/src/modifiers/replaceUnicodeWithEmojis.js
=> [WIP] Replace emojis on onChange

draft-js-counter-plugin/package.json, draft-js-counter-plugin/src/CharCounter/__test__/index.js, draft-js-counter-plugin/src/CharCounter/index.js
=> Character Counter can now properly handle unicode/emojis

docs/client/components/pages/Home/index.js
@nikgraf here it is, thanks again!
=> added myself (adrian) to the team list

docs/client/components/pages/Counter/index.js
Minor wrong filename issue in docs.
=> Fix wrong filename in counter example

docs/client/components/pages/Emoji/index.js, docs/client/components/pages/Emoji/webpackImport.js, docs/client/components/pages/Hashtag/index.js, docs/client/components/pages/Linkify/index.js, docs/client/components/pages/Linkify/webpackImport.js, docs/client/components/pages/Mention/index.js, docs/client/components/pages/Mention/webpackImport.js, docs/client/components/pages/Sticker/index.js, docs/client/components/pages/Sticker/webpackImport.js, docs/client/components/pages/Undo/index.js, docs/client/components/pages/Undo/webpackImport.js, draft-js-emoji-plugin/README.md, draft-js-undo-plugin/src/RedoButton/__test__/index.js, draft-js-undo-plugin/src/UndoButton/__test__/index.js
There are a bunch of references to the hashtag plugin from non-hashtag plugins.
=> Fix hashtag references

draft-js-emoji-plugin/src/Emoji/index.js, draft-js-emoji-plugin/src/index.js
to use another caching service/offline
=> Get image path svg as a parameter

draft-js-emoji-plugin/src/EmojiSuggestions/index.js, draft-js-mention-plugin/src/MentionSuggestions/index.js
fixes https://github.com/draft-js-plugins/draft-js-plugins/issues/266
=> Returns array for IE11 compatibilty

draft-js-toolbar-plugin/src/actions/blockTypes.js
[DraftBlockType](https://github.com/facebook/draft-js/blob/master/src/model/constants/DraftBlockType.js)
=> fixed block type naming mistake

draft-js-plugins-editor/src/Editor/__test__/index.js, draft-js-plugins-editor/src/Editor/index.js
=> Adds callback for willUnmount

draft-js-mention-plugin/src/MentionSuggestions/__test__/index.js, draft-js-mention-plugin/src/MentionSuggestions/index.js
=> Close mention suggestions when suggestions filtered results are empty

README.md
Discussed here https://github.com/draft-js-plugins/draft-js-plugins/issues/49 :)
=> Added richbuttons plugin to community list

draft-js-alignment-plugin/README.md, draft-js-alignment-plugin/src/index.js, draft-js-cleanup-empty-plugin/README.md, draft-js-cleanup-empty-plugin/src/index.js, draft-js-dnd-plugin/README.md, draft-js-entity-props-plugin/README.md, draft-js-focus-plugin/README.md, draft-js-focus-plugin/src/index.js, draft-js-image-plugin/README.md, draft-js-image-plugin/src/index.js, draft-js-mention-plugin/README.md, draft-js-resizeable-plugin/README.md, draft-js-table-plugin/README.md, draft-js-table-plugin/src/index.js, draft-js-toolbar-plugin/README.md, draft-js-toolbar-plugin/src/index.js
Update the plugin `README.md`s with very basic info.
Also standardised the `config` param in all plugins.
Fixes: #322
=> Basic README.md tidy up for new plugins

draft-js-emoji-plugin/src/EmojiSuggestions/index.js, draft-js-mention-plugin/src/MentionSuggestions/Entry/Avatar/index.js, draft-js-mention-plugin/src/MentionSuggestions/index.js
=> Remove all <noscript> tags

draft-js-mention-plugin/src/MentionSuggestions/index.js
Fixes https://github.com/draft-js-plugins/draft-js-plugins/issues/323
=> filter leaves for current line only

draft-js-mention-plugin/src/MentionSuggestions/index.js
=> fix mention's suggestions key to allow suggestion with the same name

docs/client/components/pages/Mention/CustomMentionEditor/index.js, draft-js-mention-plugin/CHANGELOG.md, draft-js-mention-plugin/src/MentionSuggestions/Entry/index.js, draft-js-mention-plugin/src/MentionSuggestions/index.js
Enables for customizations in user land:
=> pass search value to Entry component for user land customizations

draft-js-mention-plugin/src/MentionSuggestions/index.js
fix react@15.2.0 Unknown prop warning
refer to Unknown Prop Warning from draft-js-mention-plugin in react@ 15.2.0 #364
=> fix react@15.2.0 Unknown prop warning for draft-js-mention-plugin/MentionSuggestions

draft-js-mention-plugin/src/MentionSuggestions/Entry/defaultEntryComponent.js, draft-js-mention-plugin/src/MentionSuggestions/index.js
also added fixing unknown props of draft-js-mention-plugin/src/MentionSuggestions/Entry/defaultEntryComponent.js
=> Add propTypes for `mentions` list of MentionSuggestions/index.js. 

FAQ.md
info about how to add custom decorator for draft-js-plugins-editor
=> help info about how to add custom decorators

draft-js-mention-plugin/package.json
=> add mention plugin missing lodash dependency

docs/client/components/pages/Sticker/SimpleStickerEditor/index.js, draft-js-plugins-editor/CHANGELOG.md, draft-js-plugins-editor/src/Editor/__test__/index.js, draft-js-plugins-editor/src/Editor/index.js, draft-js-sticker-plugin/CHANGELOG.md, draft-js-sticker-plugin/src/index.js
custom block should have mapping reference in blockRenderMap
refer to https://github.com/draft-js-plugins/draft-js-plugins/issues/383
=> temporary fix for sticker

draft-js-mention-plugin/package.json, draft-js-mention-plugin/src/mentionSuggestionsStrategy.js, package.json
@Zhouzi any downsides doing this? feels more lightweight now using the whole lodash chain for one function :)
=> move to single lodash.escaperegexp package for mention

draft-js-mention-plugin/src/mentionSuggestionsStrategy.js
refer to https://github.com/draft-js-plugins/draft-js-plugins/issues/419
=> add Chinese support in mention plugin

draft-js-mention-plugin/src/MentionSuggestions/__test__/index.js, draft-js-mention-plugin/src/MentionSuggestions/index.js
fix issues from https://github.com/draft-js-plugins/draft-js-plugins/issues/388
=> add checking logic for getPortalClientRect and onMentionSelect.

draft-js-mention-plugin/src/MentionSuggestions/index.js
=> Fixed up arrow not looping

draft-js-mention-plugin/CHANGELOG.md
Change log entries for the 2 patches I made.
=> Added my two recent fixes to the change log

draft-js-video-plugin/src/video/components/DefaultVideoComponent.js
Update to support 16:9 ratio. (width: parrent width size)
=> Update to support 16:9 ratio.

CONTRIBUTING.md
=> How to use your own fork in your development projects

draft-js-mention-plugin/src/mentionSuggestionsStrategy.js
add korean trigger for mention plugin
=> [draft-js-mention-plugin] add support for korean characters

docs/client/components/pages/Home/index.js
changed to link from current twitter profile image from @adrianmcli
=> fix broken image from Adrian Li

docs/README.md, docs/client/components/pages/Hashtag/CustomHashtagEditor/index.js, docs/client/components/pages/SideToolbar/webpackImport.js
- Incorrect css import in side-toolbar-plugin
- Fix custom hashtag example
- Update docs README
Note a few other small doc updates have yet to be pushed live to draft-js-plugins.com
Thanks
=> Update docs README, side-toolbar-plugin, hashtag-plugin

draft-js-undo-plugin/README.md
Removed onChange and editorState props
Added passing undoPlugin to editor prop plugins
=> Updated usage in docs [undo]

README.md
Hi,
Added [Markdown Shortcuts Plugin](https://github.com/ngs/draft-js-markdown-shortcuts-plugin/) here as well as https://github.com/nikgraf/awesome-draft-js/pull/23
Thanks,
=> Add Markdown Shortcuts Plugin to community plugins

draft-js-alignment-plugin/package.json, draft-js-counter-plugin/package.json, draft-js-dnd-plugin/package.json, draft-js-emoji-plugin/package.json, draft-js-focus-plugin/package.json, draft-js-hashtag-plugin/package.json, draft-js-image-plugin/package.json, draft-js-inline-toolbar-plugin/package.json, draft-js-linkify-plugin/package.json, draft-js-mention-plugin/package.json, draft-js-plugins-editor/package.json, draft-js-resizeable-plugin/package.json, draft-js-side-toolbar-plugin/package.json, draft-js-sticker-plugin/package.json, draft-js-undo-plugin/package.json, legacy/draft-js-cleanup-empty-plugin/package.json, legacy/draft-js-entity-props-plugin/package.json, legacy/draft-js-table-plugin/package.json, npm-shrinkwrap.json, package.json
A little anxious to use, will be able to merge and publish it ?
thank you very much
=> keep sync with the immutable version of draft-js

draft-js-counter-plugin/src/index.js, draft-js-dnd-plugin/src/index.js, draft-js-emoji-plugin/src/index.js, draft-js-focus-plugin/src/index.js, draft-js-hashtag-plugin/src/index.js, draft-js-image-plugin/src/index.js, draft-js-inline-toolbar-plugin/src/index.js, draft-js-linkify-plugin/src/index.js, draft-js-mention-plugin/src/index.js, draft-js-side-toolbar-plugin/src/index.js, draft-js-sticker-plugin/src/index.js
=> Changed export default from varname to expression

draft-js-alignment-plugin/package.json, draft-js-buttons/package.json, draft-js-counter-plugin/package.json, draft-js-drag-n-drop-plugin/package.json, draft-js-drag-n-drop-upload-plugin/package.json, draft-js-emoji-plugin/package.json, draft-js-focus-plugin/package.json, draft-js-hashtag-plugin/package.json, draft-js-image-plugin/package.json, draft-js-inline-toolbar-plugin/package.json, draft-js-linkify-plugin/package.json, draft-js-mention-plugin/package.json, draft-js-plugins-editor/package.json, draft-js-resizeable-plugin/package.json, draft-js-side-toolbar-plugin/package.json, draft-js-sticker-plugin/package.json, draft-js-undo-plugin/package.json, legacy/draft-js-cleanup-empty-plugin/package.json, legacy/draft-js-entity-props-plugin/package.json, legacy/draft-js-table-plugin/package.json
Hi,
Please check.
ref: https://github.com/draft-js-plugins/draft-js-plugins/issues/549
=> Move react to `peerDependencies`

draft-js-mention-plugin/src/MentionSuggestions/index.js
To solve the bug here ：https://github.com/draft-js-plugins/draft-js-plugins/issues/619
Hope can merge it
=> Solve bug mentioned

draft-js-mention-plugin/src/MentionSuggestions/index.js
Here's an ultra simple fix for bug https://github.com/draft-js-plugins/draft-js-plugins/issues/469
=> Reopens mentions dropdown if new suggestions are available.

docs/client/components/pages/Mention/CustomComponentMentionEditor/index.js
=> Fixed CustomComponentMentionEditor segmention bug

draft-js-video-plugin/.babelrc, draft-js-video-plugin/package.json
Lacks some configuration in video plugin build. 
As a result, css is missing in the package and exception occurs.
I'm copy .babelrc from image plugin.
Please update npm package draft-js-video-plugin
=> fix video plugin build

HOW_TO_CREATE_A_PLUGIN.md
I believe Webhooks is the wrong term in this case
=> Change Webhooks to Hooks in plugin creation docs

docs/client/components/pages/Mention/index.js, draft-js-mention-plugin/CHANGELOG.md, draft-js-mention-plugin/src/index.js
Enables overriding the `MentionSuggestions` component to allow more flexible rendering of the suggestions dropdown.
=> Custom mention suggestions

draft-js-mention-plugin/src/MentionSuggestions/index.js
=> Fix #633 mentions dropdown props update

draft-js-focus-plugin/webpack.config.js
=> fix focus plugin css classnames

draft-js-mention-plugin/src/defaultRegExp.js
=> Add cyrillic symbols support in mention regexp

FAQ.md, docs/client/components/pages/Hashtag/index.js
Closes https://github.com/draft-js-plugins/draft-js-plugins/pull/826
=> document plugin order

README.md
Added some plugins that were missing in the list of plugins shown in the README.
=> Add missing plugins to list

draft-js-emoji-plugin/src/components/EmojiSelect/Popover/Nav/Entry/index.js, draft-js-undo-plugin/src/RedoButton/index.js, draft-js-undo-plugin/src/UndoButton/index.js
=> added type='button' where missing

FAQ.md, docs/client/components/pages/Mention/SimpleMentionEditor/mentions.js, docs/client/components/pages/Mention/index.js, draft-js-mention-plugin/src/MentionSuggestions/__test__/index.js, draft-js-mention-plugin/src/MentionSuggestions/index.js, draft-js-mention-plugin/src/index.js, draft-js-mention-plugin/src/utils/defaultSuggestionsFilter.js
Allow using an array for mention suggestions
fixes #864 
I'm a little confused about how changelogs work with draft-js-plugins actually ...
=> allow non immutable list for suggestions

draft-js-mention-plugin/src/MentionSuggestions/index.js, draft-js-mention-plugin/src/modifiers/addMention.js, draft-js-mention-plugin/src/utils/__test__/getTypeByTrigger.js, draft-js-mention-plugin/src/utils/getSearchText.js
Just added the support for >1 character in the mention plugin
I needed this plugin to support more than one characters so I implemented it.. 😄
=> add support for multiple characters

draft-js-plugins-editor/src/Editor/index.js
Other with the DOM will have <div class="false" ...
=> blockStyleFn should return '' instead of false.

draft-js-linkify-plugin/src/Link/index.js, draft-js-linkify-plugin/src/index.js
https://dev.to/ben/the-targetblank-vulnerability-by-example
=> Adding rel config

draft-js-mention-plugin/CHANGELOG.md, draft-js-mention-plugin/package.json, draft-js-mention-plugin/src/MentionSuggestions/index.js, draft-js-mention-plugin/src/mentionSuggestionsStrategy.js, stories/Mention/MentionEditorWithCustomTrigger/editorStyles.css, stories/Mention/MentionEditorWithCustomTrigger/index.js, stories/Mention/MentionEditorWithCustomTrigger/mentions.js, stories/index.js
fixes #881
- add story with custom mention trigger which needs escaping (for testing)
- update regexp escaping (use String.raw) to properly escape regex strings...
BOOOYAAAAH
=> Fix mention regex for characters which need escaping!!!!

docs/client/components/pages/Home/UnicornEditor/mentions.js, docs/client/components/pages/Home/index.js, docs/client/components/pages/Mention/CustomComponentMentionEditor/mentions.js, docs/client/components/pages/Mention/CustomMentionEditor/mentions.js, docs/client/components/pages/Mention/RemoteMentionEditor/index.js, docs/client/components/shared/GithubButton/index.js, docs/client/components/shared/SocialBar/index.js, docs/template.js, stories/Mention/CustomComponentMentionEditor/mentions.js, stories/Mention/CustomMentionEditor/mentions.js, stories/index.js
- Using plain javascript arrays instead of Immutable.List for mention suggestions (docs, stories)
- Using new github-buttons api (fixes deprecation warning in docs)
- Fixing typo
- Removing unused css reference
=> Fix some deprecation warnings in docs

docs/client/components/pages/Home/UnicornEditor/index.js, docs/client/components/pages/Home/UnicornEditor/initialState.js, docs/client/components/pages/Home/index.js
=> Improve example

docs/client/components/pages/Focus/index.js
It is under focus plugin document, so change alignment to focus.
=> doc: change alignment to focus

draft-js-focus-plugin/src/modifiers/insertNewLine.js
=> fix newline linked to entity

draft-js-emoji-plugin/CHANGELOG.md, draft-js-emoji-plugin/src/emojiStyles.css, draft-js-emoji-plugin/src/utils/emojiList.js
Emoji `:heart:` in priority list won't be displayed correctly (see #925 ).
Fix the incorrect Unicode code of `:heart:`.
=> Fix code of heart emoji

draft-js-emoji-plugin/src/components/EmojiSelect/Popover/index.js, draft-js-emoji-plugin/src/components/EmojiSelect/index.js
Reverts draft-js-plugins/draft-js-plugins#971
=> Revert "Rendering emoji select popover only on emoji select button press"

draft-js-emoji-plugin/CHANGELOG.md, draft-js-emoji-plugin/src/components/EmojiSuggestions/index.js
I fixed some bugs of emoji-plugin.
Maybe [this](https://github.com/draft-js-plugins/draft-js-plugins/issues/1041), and the bug of following image.
I was in reference to implementation of mention-plugin. https://github.com/draft-js-plugins/draft-js-plugins/blob/656079cf2bbda71930022013f6c3e521b12667d8/draft-js-mention-plugin/src/MentionSuggestions/index.js#L99
=> Fix behavior of emoji-plugin

docs/client/components/pages/InlineToolbar/CustomInlineToolbarEditor/index.js, stories/InlineToolbar/CustomInlineToolbarEditor/index.js
=> Fixed overrideContent feature in InlineToolbar

draft-js-resizeable-plugin/CHANGELOG.md, draft-js-resizeable-plugin/package.json, draft-js-resizeable-plugin/src/createDecorator.js
#582 
add condition for calculate width in dragging
=> fixed incorrect behavior when resized from the left edge

draft-js-mention-plugin/CHANGELOG.md, draft-js-mention-plugin/package.json, draft-js-mention-plugin/src/Mention/__test__/index.js, draft-js-mention-plugin/src/Mention/index.js, draft-js-mention-plugin/src/MentionSuggestions/Entry/Avatar/index.js, draft-js-mention-plugin/src/MentionSuggestions/Entry/defaultEntryComponent.js, draft-js-mention-plugin/src/MentionSuggestions/__test__/index.js, draft-js-mention-plugin/src/MentionSuggestions/index.js, draft-js-mention-plugin/src/index.js, draft-js-mention-plugin/src/modifiers/addMention.js, draft-js-mention-plugin/src/utils/defaultSuggestionsFilter.js, draft-js-mention-plugin/src/utils/positionSuggestions.js, package.json
=> Mentions 3.0

docs/client/components/pages/Home/UnicornEditor/initialState.js, draft-js-image-plugin/CHANGELOG.md, draft-js-image-plugin/package.json, draft-js-image-plugin/src/index.js, draft-js-image-plugin/src/modifiers/addImage.js
=> Fixes image entity name

docs/client/components/pages/Focus/webpackImport.js
=> [doc] wrong style file in focus's document

draft-js-focus-plugin/CHANGELOG.md, draft-js-focus-plugin/package.json, draft-js-focus-plugin/src/createDecorator.js
=> Change unsafe componentWillMount to componentDidMount lifecycle hook.

draft-js-mention-plugin/CHANGELOG.md, draft-js-mention-plugin/package.json, draft-js-mention-plugin/src/utils/__test__/getSearchTextAt.js, draft-js-mention-plugin/src/utils/getSearchTextAt.js
fix #1182 
add condition for getting `matchingString`
=> fix(mention): allow emptyp mentionTrigger

draft-js-divider-plugin/src/index.js
As per #1179, this is a proof of concept, I'm afraid I don't have the time or knowledge to fork/compile/test as my webpack knowledge is very limited.
=> Allow custom divider button

docs/client/components/pages/Focus/index.js
#979 
add `Configuration Parameters` section
=> docs(focus-plugin): add section for Configuration Parameters

docs/client/components/pages/Anchor/CustomInlineToolbarEditor/index.js, docs/client/components/pages/Anchor/SimpleLinkPluginEditor/index.js, docs/client/components/pages/InlineToolbar/CustomInlineToolbarEditor/index.js, draft-js-inline-toolbar-plugin/CHANGELOG.md, draft-js-inline-toolbar-plugin/package.json, draft-js-inline-toolbar-plugin/src/components/Toolbar/__test__/Toolbar.js, draft-js-inline-toolbar-plugin/src/components/Toolbar/index.js, draft-js-inline-toolbar-plugin/src/index.js, stories/inline-toolbar-custom-buttons/src/App.js, stories/inline-toolbar-with-anchor-plugin/src/App.js
Swap structure prop for render props (children)
=> WIP: Refactor inline-toolbar via render props

docs/client/components/pages/StaticToolbar/CustomToolbarEditor/index.js, draft-js-static-toolbar-plugin/CHANGELOG.md, draft-js-static-toolbar-plugin/package.json, draft-js-static-toolbar-plugin/src/components/Toolbar/index.js, draft-js-static-toolbar-plugin/src/index.js, package.json, stories/static-toolbar-custom-buttons/src/App.js, yarn.lock
=> Refactor static toolbar via render prop

draft-js-static-toolbar-plugin/src/components/Toolbar/__test__/Toolbar.js, package.json, yarn.lock
Finally all tests are passing.
=> Fix static toolbar test

draft-js-alignment-plugin/src/createDecorator.js, draft-js-resizeable-plugin/src/createDecorator.js
=> Fix wrapper component names in a couple of decorators

draft-js-alignment-plugin/package.json, draft-js-drag-n-drop-plugin/package.json, draft-js-drag-n-drop-upload-plugin/package.json, draft-js-focus-plugin/package.json, draft-js-hashtag-plugin/package.json, draft-js-image-plugin/package.json, draft-js-inline-toolbar-plugin/package.json, draft-js-linkify-plugin/package.json, draft-js-resizeable-plugin/package.json, draft-js-sticker-plugin/package.json, package.json
=> Remove prop-types where not used

draft-js-alignment-plugin/package.json, draft-js-drag-n-drop-plugin/package.json, draft-js-drag-n-drop-upload-plugin/package.json, draft-js-focus-plugin/package.json, draft-js-hashtag-plugin/package.json, draft-js-image-plugin/package.json, draft-js-inline-toolbar-plugin/package.json, draft-js-mention-plugin/package.json, draft-js-plugins-editor/package.json, draft-js-resizeable-plugin/package.json, draft-js-side-toolbar-plugin/package.json, draft-js-static-toolbar-plugin/package.json, draft-js-sticker-plugin/package.json, package.json
Only emoji plugin uses this package. No need to list it in every plugin.
=> Remove find-with-regex where not used

draft-js-alignment-plugin/package.json, draft-js-counter-plugin/package.json, draft-js-drag-n-drop-upload-plugin/package.json, draft-js-hashtag-plugin/package.json, draft-js-image-plugin/package.json, draft-js-inline-toolbar-plugin/package.json, draft-js-linkify-plugin/package.json, draft-js-resizeable-plugin/package.json, draft-js-side-toolbar-plugin/package.json, draft-js-static-toolbar-plugin/package.json, draft-js-undo-plugin/package.json, draft-js-video-plugin/package.json, package.json
=> Remove immutable from packages where not used

.eslintignore, draft-js-anchor-plugin/package.json, draft-js-anchor-plugin/src/index.d.ts, draft-js-buttons/package.json, draft-js-buttons/src/index.d.ts, draft-js-drag-n-drop-plugin/package.json, draft-js-drag-n-drop-plugin/src/index.d.ts, draft-js-emoji-plugin/package.json, draft-js-emoji-plugin/src/index.d.ts, draft-js-focus-plugin/package.json, draft-js-focus-plugin/src/index.d.ts, draft-js-image-plugin/package.json, draft-js-image-plugin/src/index.d.ts, draft-js-inline-toolbar-plugin/package.json, draft-js-inline-toolbar-plugin/src/index.d.ts, draft-js-plugins-editor/package.json, draft-js-plugins-editor/src/index.d.ts, draft-js-resizeable-plugin/package.json, draft-js-resizeable-plugin/src/index.d.ts, package.json, yarn.lock
Add typescript typings for the core components and some of the plugins.
This can serve as a starting point for adding types to the other
plugins.
=> Add some typescript typings

.flowconfig, draft-js-focus-plugin/src/index.js, draft-js-plugins-editor/src/Editor/defaultKeyCommands.js, package.json, yarn.lock
eventTimeStamp is added as a third argument to handleKeyCommand.
Ideally better design would be to pass plugins functions as first
argument so any new api would not break existing plugins.
Closes #1300 and #1297
=> [breaking] upgrade to draft v0.11

draft-js-emoji-plugin/CHANGELOG.md, draft-js-emoji-plugin/package.json, draft-js-focus-plugin/CHANGELOG.md, draft-js-focus-plugin/package.json, draft-js-mention-plugin/CHANGELOG.md, draft-js-mention-plugin/package.json
- draft-js-emoji v2.1.3
- draft-js-focus-plugin v3.0.1
- draft-js-mention-plugin v3.1.5
=> Bump version

draft-js-emoji-plugin/CHANGELOG.md, draft-js-emoji-plugin/package.json, draft-js-mention-plugin/CHANGELOG.md, draft-js-mention-plugin/package.json, package.json, rollup.config.js, yarn.lock
This will allow to exclude lodash from commonjs plugin in my project.
=> Use lodash-es in esm bundle

docs/client/components/pages/Mention/CustomComponentMentionEditor/index.js, docs/client/components/pages/Mention/CustomMentionEditor/index.js, docs/client/components/pages/Mention/RemoteMentionEditor/index.js, docs/client/components/pages/Mention/SimpleMentionEditor/index.js, docs/client/components/pages/Mention/index.js, draft-js-mention-plugin/CHANGELOG.md, draft-js-mention-plugin/src/MentionSuggestions/__test__/index.js, draft-js-mention-plugin/src/MentionSuggestions/index.js, draft-js-mention-plugin/src/utils/positionSuggestions.js, stories/mentions-custom-component/src/App.js, stories/mentions-custom-styled/src/App.js, stories/mentions-custom-trigger/src/App.js, stories/mentions-remote/src/App.js, stories/mentions-with-whitespace/src/App.js, stories/mentions/src/App.js
See changelog and stories/mentions/src/App.js
- dropped UNSAFE_ hooks
- made suggestions open state controlled
=> [mention-plugin] make open state controlled

README.md
=> Make clear that we're looking for maintainers

draft-js-plugins-editor/src/index.d.ts
Fixes https://github.com/draft-js-plugins/draft-js-plugins/issues/1360
=> fix(Editor): allow undefined return for keyBindingFn

draft-js-emoji-plugin/CHANGELOG.md, draft-js-emoji-plugin/src/index.js
RE https://github.com/draft-js-plugins/draft-js-plugins/issues/1260
=> [emoji-plugin] Fix selection on insert

.eslintrc, .travis.yml, jest.config.js, jestHelper.js, package.json, testHelper.js, yarn.lock
-- not applied
In order to contribute with @sibelius on some tooling migration, this PR adds new testing tools
Adds jest + react-testing-library with some basic config
=> adding jest configs and react-testing-library with extra dom assertions

draft-js-mention-plugin/CHANGELOG.md, draft-js-mention-plugin/src/defaultRegExp.js
=> [mention-plugin] add support for Arabic

docs/client/components/pages/Mention/styles.css
Fix typo
these checks seem to be non-applicable.
Fixes issue #1443
With fix applied:
=> Update styles.css for Mention-documentation

draft-js-buttons/src/index.d.ts
=> fix function types (#1433)

draft-js-buttons/src/index.d.ts, draft-js-inline-toolbar-plugin/src/index.d.ts
Addresses https://github.com/draft-js-plugins/draft-js-plugins/issues/1423.
The issue stems from the fact that `draft-js-buttons` defines `DraftJsButtonTheme` as an interface with required properties, but `draft-js-inline-toolbar` makes those same properties optional.
While doing some testing by providing a config to the toolbar in my personal project, it became obvious that the optionality of the properties in the theme object were backwards:
1. If you provide a `theme` object without `buttonStyles` or `toolbarStyles` to `draft-js-inline-toolbar-plugin` there will be an error on accesses like [this …
=> [types fix] flip optionals - make classnames optional but theme components required

draft-js-mention-plugin/src/index.js
=> export addMention from index.js fixes #1416

.github/stale.yml
Mark as stale and close inactive issues.
Integration of [stale bot](https://github.com/probot/stale)
=> Set up stale bot

draft-js-mention-plugin/src/Mention.js, draft-js-mention-plugin/src/Mention/__test__/Mention.test.js
Resolving #1477 
Migrating Mention plugin test to Testing Library
=> feat(test): migrating mention-plugin test

draft-js-focus-plugin/src/index.d.ts
Added configuration for focus plugin
=> Fix create focus plugin typings

packages/editor/src/Editor/PluginHooks.ts, packages/editor/src/index.ts, packages/emoji/src/index.tsx, packages/focus/src/index.tsx, packages/mention/src/index.tsx
See issue #1601
Revert to original version where undefined is used chain through multiple unhandled keyBindingFn
=> Fixing return value of keyBindingFn

packages/anchor/src/components/AddLinkForm.tsx
=> fix(anchor): url validation was wrong & naming of the state variable was inconsistent

packages/video/src/__test__/createVideoPlugin.test.ts
Fixes part of #1477
This PR migrates the `@draft-js-plugins/video` to TypeScript and jest
=> Migrating of @draft-js-plugins/video to jest

packages/emoji/CHANGELOG.md, packages/emoji/package.json, packages/emoji/src/__test__/emojiSuggestionsStrategy.test.ts, packages/emoji/src/components/EmojiSuggestions/index.tsx, packages/emoji/src/emojiSuggestionsStrategy.ts
See issue #1645
Fixing regular expression to include `:` at the end of a string.
=> Fixing issue with detecting : at end of word for emoji select

packages/emoji/CHANGELOG.md, packages/emoji/package.json, packages/emoji/src/components/EmojiSuggestions/index.tsx, packages/emoji/src/index.tsx
=> fixing clientRectFunctions.get(...) is not a function

packages/emoji/CHANGELOG.md, packages/emoji/package.json, packages/emoji/src/components/EmojiSuggestions/index.tsx, packages/emoji/src/index.tsx, packages/mention/CHANGELOG.md, packages/mention/package.json, packages/mention/src/MentionSuggestions/MentionSuggestions.tsx
Fixing issue https://github.com/draft-js-plugins/draft-js-plugins/issues/1697
Return `undefined` for `keBindingFn`.
=> Fixing issue DOMException: Failed to execute 'removeChild' on 'Node'

packages/anchor/CHANGELOG.md, packages/anchor/package.json, packages/anchor/src/components/LinkButton.tsx
=> fixing getEditorState can be undefined

packages/mention/CHANGELOG.md, packages/mention/package.json, packages/mention/src/MentionSuggestions/MentionSuggestions.tsx
=> Fix key bindings issue if dropdown is open but there's no suggestion

packages/alignment/package.json, packages/anchor/package.json, packages/buttons/package.json, packages/counter/package.json, packages/divider/package.json, packages/drag-n-drop-upload/package.json, packages/drag-n-drop/package.json, packages/editor/package.json, packages/emoji/package.json, packages/focus/package.json, packages/hashtag/package.json, packages/image/package.json, packages/inline-toolbar/package.json, packages/linkify/package.json, packages/mention/package.json, packages/resizeable/package.json, packages/side-toolbar/package.json, packages/static-toolbar/package.json, packages/sticker/package.json, packages/undo/package.json, packages/video/package.json
A lot of warnings while installation and I guess a lot of headaches for npm 7 users.
Upgraded peer dependencies in all packages
=> Support react 17 in peer dependencies

packages/mention/src/__test__/Mention.test.tsx
=> [Mention Plugin] Fixing file name and test

packages/alignment/src/index.tsx, packages/drag-n-drop-upload/src/modifiers/modifyBlockData.ts, packages/drag-n-drop-upload/src/modifiers/replaceBlock.ts, packages/drag-n-drop/src/modifiers/addBlock.ts, packages/drag-n-drop/src/modifiers/removeBlock.ts, packages/focus/src/modifiers/removeBlock.ts
Fixing the lint warning about missing function names
=> [Linting] Add missing function names

stories/public/data/mentionsA.json, stories/public/data/mentionsB.json, stories/public/data/mentionsC.json
The storybook example `Editor with Mention Plugin and asynchronously loaded suggestions` is missing the data files. This PR adds them.
=> add missing data files

packages/emoji/CHANGELOG.md, packages/emoji/package.json
=> [Emoji Plugin] 4.2.0 release

.storybook/webpack.config.js, jest.config.base.js, package.json, packages/emoji/package.json, packages/emoji/src/index.tsx, packages/mention/package.json, packages/mention/src/MentionSuggestions/MentionSuggestions.tsx, packages/mention/src/mentionSuggestionsStrategy.ts, rollup.config.js, yarn.lock
This PR remove `lodash` and replaces it with `lodash-es`.
=> Change lodash to lodash-es

package.json, yarn.lock
Reverts draft-js-plugins/draft-js-plugins#1824
=> Revert "chore(deps-dev): bump @babel/core from 7.12.17 to 7.13.1"

packages/anchor/CHANGELOG.md, packages/anchor/package.json, packages/anchor/src/components/AddLinkForm.tsx, packages/anchor/src/components/DefaultLinkButton.tsx, packages/anchor/src/components/LinkButton.tsx, packages/anchor/src/index.tsx, packages/inline-toolbar/CHANGELOG.md, packages/inline-toolbar/package.json, packages/inline-toolbar/src/components/Toolbar/index.tsx, stories/inline-toolbar-with-anchor-plugin/src/AnchorSimpleLinkPluginEditor.tsx, tsconfig.json
=> Fixing TypeScript issue between anchor plugin and inline toolbar plugin

CHANGELOG.md, packages/mention/CHANGELOG.md, packages/mention/src/__test__/mentionSuggestionsStrategy.test.ts, packages/mention/src/mentionSuggestionsStrategy.ts
=> [Mention Plugin] fixing whitespace support for safari

CHANGELOG.md, packages/mention/CHANGELOG.md, packages/mention/package.json, packages/mention/src/__test__/mentionSuggestionsStrategy.test.ts, packages/mention/src/mentionSuggestionsStrategy.ts
=> [Mention Plugin] fixing trigger range

packages/docs/components/Examples/mention/CustomComponentMentionEditor/CustomComponentMentionEditor.tsx, packages/docs/components/Examples/mention/RemoteMentionEditor/RemoteMentionEditor.tsx, packages/docs/components/Examples/mention/SimpleMentionEditor/SimpleMentionEditor.tsx
=> [docs] fixing initial open state in examples

.github/workflows/deployWebsite.yml, scripts/publishGithubPages.sh
This PR adds a github workflow to publish the github website on demand
=> Add workflow to publish github website

CHANGELOG.md, packages/mention/CHANGELOG.md, packages/mention/src/MentionSuggestions/MentionSuggestions.tsx
Fix the @ mentions to actually work. right now they don't work in the middle of a line. if you start a line with "@" it works but if you start typing text then type "@" it doesn't work.
=> Fix multi trigger issue

packages/mention/CHANGELOG.md, packages/mention/package.json, packages/mention/src/defaultRegExp.ts
=> [Mention Plugin] extend support for chinese symbols

packages/docs/pages/plugin/hashtag/index.js, packages/docs/pages/plugin/hashtag/styles.module.css, packages/hashtag/CHANGELOG.md, packages/hashtag/package.json, packages/hashtag/src/Hashtag.tsx, packages/hashtag/src/index.tsx
=> [Hashtag Plugin] add hashtagComponent to config

packages/docs/pages/plugin/emoji/index.js, packages/emoji/CHANGELOG.md, packages/emoji/package.json, packages/emoji/src/components/Emoji/NativeEmojiImage.tsx, packages/emoji/src/components/EmojiSelect/Popover/Entry/index.tsx, packages/emoji/src/components/EmojiSuggestions/Entry/index.tsx, packages/emoji/src/index.tsx
=> [Emoji Plugin] Add unicode to emoji image component

packages/emoji/CHANGELOG.md, packages/emoji/package.json, packages/emoji/src/components/EmojiSelect/Popover/index.tsx
#855
Render Emoji Select content only if popup is open
=> [Emoji plugin] render popup content only if open

packages/docs/components/Examples/emoji/CustomEmojiEditor/index.js, packages/docs/pages/plugin/emoji/index.js, packages/emoji/CHANGELOG.md, packages/emoji/package.json, packages/emoji/src/components/EmojiSelect/Popover/index.tsx, packages/emoji/src/components/EmojiSelect/index.tsx, stories/emoji/src/SimpleEmojiEditor.tsx
=> [Emoji Plugin] Close EmojiSelect after selection

packages/focus/CHANGELOG.md, packages/focus/package.json, packages/focus/src/index.tsx
=> [Focus Plugin] Check if the selection still has focus

packages/mention/CHANGELOG.md, packages/mention/src/utils/positionSuggestions.ts
=> [Mention Plugin] Add store to PositionSuggestionsParams types

packages/mention/CHANGELOG.md, packages/mention/package.json, packages/mention/src/MentionSuggestions/MentionSuggestions.tsx
=> [Mention Plugin] Fixing issue if trigger is first character

packages/drag-n-drop/CHANGELOG.md, packages/drag-n-drop/package.json, packages/drag-n-drop/src/createDecorator.tsx
=> [Drag'n'Drop Plugin] Add missing forwardRef for image component

packages/mention/CHANGELOG.md, packages/mention/package.json, packages/mention/src/MentionSuggestions/MentionSuggestions.tsx, stories/mentions-custom-styled/src/CustomMentionEditor.stories.tsx
=> [Mention Plugin] fixing line break on mentions

.github/dependabot.yml, packages/docs/next.config.js, packages/docs/package.json, packages/docs/pages/plugin/mention/index.tsx, yarn.lock
Fixing names of CSS files shown in the documentation. Also fixes issues with updated `animateplus` library
closes #2015
=> [Docs] fixing names of css files

package.json, packages/emoji/CHANGELOG.md, packages/emoji/package.json, packages/emoji/src/@types/react-custom-scrollbars-2.d.ts, packages/emoji/src/components/EmojiSelect/Popover/Groups/index.tsx, yarn.lock
=> [Emoji Plugin] Change to react-custom-scrollbars-2

packages/mention/CHANGELOG.md, packages/mention/package.json, packages/mention/src/__test__/mentionSuggestionsStrategy.test.ts, packages/mention/src/mentionSuggestionsStrategy.ts
=> [Mention Plugin] Fixing multi-character trigger

packages/mention/CHANGELOG.md, packages/mention/src/utils/__test__/getSearchTextAt.test.ts, packages/mention/src/utils/getSearchTextAt.ts
=> [Mention plugin] Remove the trigger from the search value

packages/docs/components/Examples/static-toolbar/CustomToolbarEditor/index.js, packages/docs/components/Examples/static-toolbar/SimpleToolbarEditor/index.js, packages/docs/components/Examples/static-toolbar/ThemedToolbarEditor/index.js
Fixing issue with SSR and nextjs. 
See also https://github.com/facebook/draft-js/issues/2332#issuecomment-761573306
closes #2036
=> [Docs] fixing issue with SSR

packages/docs/pages/plugin/emoji/index.js, packages/emoji/CHANGELOG.md, packages/emoji/package.json, packages/emoji/src/index.tsx
=> [Emojis Plugin] Add prop to disable emoji suggestions

packages/docs/components/Examples/side-toolbar/CustomSideToolbarEditor/index.js, packages/docs/components/Examples/side-toolbar/SimpleSideToolbarEditor/index.js, packages/docs/pages/plugin/side-toolbar/index.js, packages/docs/pages/plugin/side-toolbar/styles.module.css, packages/side-toolbar/CHANGELOG.md, packages/side-toolbar/package.json, packages/side-toolbar/src/components/Toolbar/Popover.tsx, packages/side-toolbar/src/components/Toolbar/index.tsx, packages/side-toolbar/src/index.tsx
closes #2054
`popper.js` can be controlled by the new `popperOptions` config parameter which is used for initialization.
Before:
After:
=> [Side Toolbar] Change to popper.js

.storybook/main.js, packages/resizeable/CHANGELOG.md, packages/resizeable/package.json, packages/resizeable/src/createDecorator.tsx
=> [Resizeable Plugin] Fixing issue with incorrect sizes

packages/docs/package.json, packages/drag-n-drop/package.json, packages/editor/package.json, packages/emoji/package.json, packages/focus/package.json, packages/mention/package.json, packages/sticker/package.json, yarn.lock
Reverts draft-js-plugins/draft-js-plugins#2195
See also #1710
=> Revert "Bump immutable from 4.0.0-rc.12 to 4.0.0-rc.14"

packages/docs/env.d.ts, packages/docs/next-env.d.ts
remove type declaration from next-env.d.ts and move into separate file as it is now always recreated.
=> [docs] fixing raw-loader definition

packages/mention/CHANGELOG.md, packages/mention/package.json, packages/mention/src/MentionSuggestions/Entry/Entry.tsx, packages/mention/src/MentionSuggestions/__test__/MentionSuggestions.test.tsx
=> [Mention Plugin] sroll focused Entry component into view

packages/docs/pages/plugin/mention/index.tsx, packages/mention/CHANGELOG.md, packages/mention/package.json, packages/mention/src/MentionSuggestions/MentionSuggestions.tsx, packages/mention/src/MentionSuggestions/Popover.tsx, packages/mention/src/theme.ts
=> [Mention Plugin] Add animation for popper.js

packages/docs/next-env.d.ts, packages/docs/package.json, packages/docs/pages/_app.tsx, yarn.lock
=> [docs] upgrade next.js

package.json, packages/drag-n-drop/src/createDecorator.tsx, packages/emoji/src/components/EmojiSelect/Popover/ToneSelect/index.tsx, yarn.lock
Update to Typescript 4.4 and fixing issues
=> Update TypeScript 4.4

packages/static-toolbar/CHANGELOG.md, packages/static-toolbar/package.json, packages/static-toolbar/src/components/Toolbar/index.tsx
=> [Static Toolbar Plugin] Fixing TypeScript issue with anchor plugin

packages/docs/pages/plugin/resizeable/index.js
=> [docs] Add notes for Resizeable Plugin

.github/workflows/dependabot-auto-merge.yml
=> add auto merge

packages/docs/pages/plugin/linkify/index.js, packages/docs/pages/plugin/linkify/styles.module.css, packages/linkify/CHANGELOG.md, packages/linkify/package.json
=> [Linkify Plugin] create release

.prettierrc.js, packages/docs/components/EditOnGithub.tsx, packages/docs/components/PluginPageFrame/PluginPageFrame.tsx, packages/docs/components/SocialBar/SocialBar.module.css, packages/docs/components/SocialBar/SocialBar.tsx, packages/docs/pages/plugin/alignment/index.js, packages/docs/pages/plugin/anchor/index.js, packages/docs/pages/plugin/counter/index.js, packages/docs/pages/plugin/divider/index.js, packages/docs/pages/plugin/drag-n-drop/index.js, packages/docs/pages/plugin/emoji/index.js, packages/docs/pages/plugin/focus/index.js, packages/docs/pages/plugin/hashtag/index.js, packages/docs/pages/plugin/image/index.js, packages/docs/pages/plugin/inline-toolbar/index.js, packages/docs/pages/plugin/linkify/index.js, packages/docs/pages/plugin/mention/index.tsx, packages/docs/pages/plugin/resizeable/index.js, packages/docs/pages/plugin/side-toolbar/index.js, packages/docs/pages/plugin/static-toolbar/index.js, packages/docs/pages/plugin/sticker/index.js, packages/docs/pages/plugin/undo/index.js, packages/docs/pages/plugin/video/index.js
closes #2405
Removed "Browserify" section as there were no content.
Add "Edit on Github" link at the bottom of each page.
=> [Docs] add "Edit on Github" Link

FAQ.md, HOW_TO_CREATE_A_PLUGIN.md, packages/docs/pages/plugin/mention/index.tsx, packages/mention/CHANGELOG.md
All of the following links are Not Found.
```bash
$ git grep facebook.github.io.*.html
FAQ.md:You most probably miss this file. See also the troubleshooting in the original [DraftJS documentation](https://facebook.github.io/draft-js/docs/advanced-topics-issues-and-pitfalls.html#missing-draft-css).
HOW_TO_CREATE_A_PLUGIN.md:You can read more about it in the original Draft.js documentation about [decorators](https://facebook.github.io/draft-js/docs/advanced-topics-decorators.html#compositedecorator).
HOW_TO_CREATE_A_PLUGIN.md:If you want to implement the [DraftDecoratorType Interface](https://facebook.github.io/draft-js/docs/advanced-topics-decorators.html#beyond-compositedecorator) yourself, you can include those in your `decorators` array alongside the composite decorators. See …
```
=> [Docs]Fix not found facebook.github.io*.html links

packages/mention/CHANGELOG.md, packages/mention/package.json, packages/mention/src/utils/warning.ts
=> [Mention Plugin] adjust import for lodash

FAQ.md
=> [Chore] add FAQ for decorators

packages/drag-n-drop-upload/CHANGELOG.md, packages/drag-n-drop-upload/package.json
=> [drag-n-drop-upload Plugin] create new version

packages/docs/components/Footer/Footer.tsx, packages/docs/pages/plugin/emoji/index.js, packages/docs/pages/plugin/hashtag/index.js, packages/docs/pages/plugin/linkify/index.js, packages/docs/pages/plugin/mention/index.tsx, packages/docs/pages/plugin/resizeable/index.js, packages/docs/pages/plugin/static-toolbar/index.js
- Issue #2621 
- emojione.com -> joypixels
- fyi: https://blog.joypixels.com/emojione-is-now-joypixels/
Fix Typo
=> Fix docs typo

.eslintrc.js, packages/drag-n-drop-upload/CHANGELOG.md, packages/drag-n-drop-upload/package.json, packages/drag-n-drop-upload/src/handleDroppedFiles.ts, packages/drag-n-drop-upload/src/index.ts, packages/emoji/src/components/EmojiSelect/Popover/Entry/index.tsx, packages/emoji/src/components/EmojiSelect/Popover/Groups/Group/index.tsx, packages/mention/src/Mention.tsx, packages/mention/src/__test__/Mention.test.tsx, yarn.lock
- updated dependencies and dependencies --deep
- fixed new eslint issues
- changed `@typescript-eslint/no-explicit-any` from warning to error
=> [chore] update dependencies and fixing eslint issues

packages/mention/CHANGELOG.md, packages/mention/package.json, packages/mention/src/MentionSuggestions/MentionSuggestions.tsx, packages/mention/src/MentionSuggestions/Popover.tsx
=> [Mention Plugin] Fixing popoverContainer type

packages/buttons/CHANGELOG.md, packages/buttons/package.json, packages/buttons/src/index.ts, packages/buttons/src/utils/createBlockAlignmentButton.tsx, packages/buttons/src/utils/createBlockStyleButton.tsx, packages/buttons/src/utils/createInlineStyleButton.tsx, packages/buttons/src/utils/createTextAlignmentButton.tsx
closes #2628
Add a `buttonProps` property for buttons to set custom properties like `aria-label` to the button
=> [Buttons] Add buttonProps to customize buttons

.github/workflows/deployWebsite.yml, .github/workflows/release.yml, .github/workflows/tests.yml
Bumps the node version from 12 to 16 for the workflows
=> [Chore] Update node for workflows

babel.config.js, jestHelper.js, package.json, packages/undo/src/RedoButton/__test__/index.test.tsx, packages/undo/src/UndoButton/__test__/index.test.tsx, yarn.lock
=> [Chore] Update @testing-library/user-event to 14.1.0

package.json, packages/docs/components/UnicornEditor/UnicornEditor.tsx, packages/editor/src/Editor/createCompositeDecorator.tsx, packages/emoji/src/components/EmojiSelect/Popover/Groups/index.tsx, yarn.lock
- upgrading typescript and fixing issues
- removing postcss-loader dependency as it is not needed
- Upgrading peer dependencies
=> [chore] Upgrade dependencies

packages/text-alignment/CHANGELOG.md, packages/text-alignment/package.json, packages/text-alignment/src/TextAlignmentComponent.tsx, packages/text-alignment/src/index.tsx
=> [text-alignment plugin] Fixing TypeScript types

packages/alignment/package.json, packages/anchor/package.json, packages/buttons/package.json, packages/counter/package.json, packages/divider/package.json, packages/drag-n-drop-upload/package.json, packages/drag-n-drop/package.json, packages/editor/package.json, packages/emoji/package.json, packages/focus/package.json, packages/hashtag/package.json, packages/image/package.json, packages/inline-toolbar/package.json, packages/linkify/package.json, packages/mention/package.json, packages/mention/src/MentionSuggestionsPortal.tsx, packages/resizeable/package.json, packages/side-toolbar/package.json, packages/static-toolbar/package.json, packages/sticker/package.json, packages/text-alignment/package.json, packages/undo/package.json, packages/video/package.json
=> update react peerDependencies
